### ISSUE TITLE
best practices for gateway-proxy helm chart

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1084]
currently there are some configuration options we don't currently expose for Envoy in our helm chart

resource monitoring and buffer sizes: https://github.com/envoyproxy/envoy/pull/8001

as well as a kubernetes `preStop` hook which will call Envoy to ensure a graceful drain/shutdown: https://www.envoyproxy.io/docs/envoy/latest/operations/admin#operations-admin-interface-healthcheck-fail

**Comment by leosunmo** [comment]
I have found that I don't need the Envoy health check to fail since the Service will stop serving traffic to Envoy as soon as the Pod enters `terminating` stage (it's removed from the endpoints list).

Setting the health check to fail could actually cause more harm than good. If you use the health check mechanism in a cloud load balancer (AWS ALB in my case) it could start marking nodes as unhealthy as soon as the health check is set to fail, which could cause actual downtime.

**Comment by leosunmo** [comment]
I also make sure to add `terminationGracePeriodSeconds: 70` to my Envoy deployments since I know we could theoretically have connections last almost 60s, this way it will receive no new connections since the Service is not routing to it, and it will be given plenty of time to drain existing connections.

**Comment by rickducott** [comment]
Leaving open as it would be useful to update docs for these learnings

**Comment by ned1313** [comment]
Graceful shutdown option has been added. Closing issue.
