### ISSUE TITLE
GRPC to REST - autodiscovery

### ISSUE THREAD

**Issue by george-oakling** [solo-io/gloo#1168]
Hi,
I went through the docs, where the GRPC to REST is mentioned and I find it generally difficult to set up. Isn't there alternative to setup the REST automatically based on GRPC reflection, which already includes google.api.http option? We use grpc-gateway nowadays, but this would be awesome if possible, so we can remove the sidecar containers which are now responsible for HTTP transcoding to GRPC.

**Comment by ilackarms** [comment]
@george-oakling i'm not sure i completely understand the problem. the current model *does* use grpc reflection such as the example here: https://gloo.solo.io/gloo_routing/virtual_services/routes/route_destinations/single_upstreams/function_routing/grpc_to_rest/

Gloo doesn't currently respect the routes defined in the `google.api.http option` because the routes are already defined on your virtual services.

**Comment by george-oakling** [comment]
@ilackarms as you mention - Gloo does not respect the routes defined in `google.api.http` - but why? When I'll try to add all of my routes from `google.api.http` it would take me ages and I would have to duplicate what I have already done in `google.api.http` (we also generate swagger definitions out of protobuf definitions).

**Comment by rickducott** [comment]
Closing as stale.
