### ISSUE TITLE
Glooctl check, checks all pods, not just gloo's

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#1299]
Currently the glooctl check utility checks all pods running in a given namespace, however we should change it to check for Gloo pods by label because we ship with `app:gloo` on all of our deployments.

**Comment by leosunmo** [comment]
To add to this, it also doesn't take in to account that "Completed" state, which technically isn't ready, is not a bad thing.
For example:
```
➜ glooctl check
Checking pods... Pod gateway-certgen-tw8jx in namespace gloo-system is not ready!
Problems detected!
➜ kubectl get po
NAME                                  READY   STATUS              RESTARTS   AGE
api-server-57964c8bf6-kfvpq           3/3     Running             0          5h10m
discovery-6f4cfc797f-82tvt            1/1     Running             0          4h33m
gateway-certgen-tw8jx                 0/1     Completed           0          4h32m
gateway-controller-7c9d8fcf76-qz6p8   1/1     Running             0          19m
gloo-df58645df-5wgrg                  1/1     Running             0          4h17m
```

**Comment by byrdog55** [comment]
We would like to pass a list of `--namespaces gloo-system,gloo-portal,foo,bar` because in large environments with portal installed we see extremelely slow check times for CRs that can live in other namespaces.
`Checking upstreams... OK

Checking upstream groups... OK

Checking auth configs... OK

Checking rate limit configs... OK

Checking VirtualHostOptions... OK

Checking secrets... OK

Checking virtual services... OK

Checking gateways... OK

Checking rate limit server... OK`

**Comment by totallyGreg** [comment]
This can also cause `panic: failed to start kube shared informer factory: timed out while waiting for informer caches to sync
` in sufficiently large environments (e.g. 173 namespaces) even after setting export SOLOKIT_CACHE_SYNC_TIMEOUT="10m", glooctl check made progress further but still failed after 74 minutes.

**Comment by Bslabe123** [comment]
- check all pods with `app : gloo` label, do this by adding an --allNamespace flag that scans all namespaces and only checks pods with the `app : gloo` label

- `--namespaces` flag to check all resources over the specified namespaces

- Investigate not checking completed pods
