### ISSUE TITLE
clarify discovery behavior and upstream creation in docs

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#1328]
as features have been added to FDS/UDS, the docs have trailed and now need updates

clarify:
- what to expect from created upstreams
- how to tune discovery's behavior (currently can whitelist/blacklist/disable FDS but not UDS)

**Comment by galindro** [comment]
@rickducott why this issue was closed? I would like to being able to apply the same FDS rules in UDS... Is it possible to do it? If no, do you think that this could be possible in a next release?

**Comment by rickducott** [comment]
@galindro I closed it because it hadn't been updated in about 5 months and appeared stale. We have addressed some of the docs shortcomings mentioned in the description, but not the lack of controls around whitelisting/blacklisting UDS as you are requesting. I have updated the linked issue to reflect that. Thanks for flagging
