### ISSUE TITLE
Gateway Authentication?

### ISSUE THREAD

**Issue by mavencode01** [solo-io/gloo#139]
Any plans to support gateway authentication before proxying to upstream microservices

**Comment by yuval-k** [comment]
@mavencode01 Can you provide some more contexts? 
I'm assuming you mean authenticating end-users. What way do you currently do Auth? OIDC? Something in-house?

**Comment by mavencode01** [comment]
Yes, currently using Kong with just Basic Auth. We want to migrate to OAuth2 or OIDC. Is this a feature plan?

**Comment by ilackarms** [comment]
cc @ilevine

**Comment by yuval-k** [comment]
Envoy has support for JWT (which is is needed for OIDC) and we plan to add support for it and basic auth in gloo shortly.

**Comment by ilevine** [comment]
we have support for OIDC, JWT, Basic Auth and gloo-e: https://gloo.solo.io/enterprise/authentication/
closing as answered. please re-open if needed.

**Comment by pouledodue** [comment]
All auth stuff is Enterprise?

**Comment by ichtestemalwieder** [comment]
I was evaluating API Gateways and Gloo looks promising. But all the Authentication Features seem to be Enterprise Edition? This makes Gloo worthless for every usecase. Auth "Termination" is the main usecae for every Gateway.... 

Does Gloo support custom plugins/extensions to implement this? 

This should at least be documented somewhere, otherwise all people interested will leave the site and and start using something else. Thanks.

**Comment by pouledodue** [comment]
@ichtestemalwieder they don't give af
