### ISSUE TITLE
Gloo release process wipes old helm repo index

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1834]
During a Gloo release we download our hosted helm repo, index the new version, and upload the update.

Apparently the helm 3 libraries don't play well with helm 2 repositories, and we accidentally wiped our old helm repos with the Gloo 1.2.0 release (helm 3 support).

We had to rebuild the helm index and upload it so users could install any non-1.2.0 version of Gloo.

We need to investigate and fix this.

**Comment by kdorosh** [comment]
This is because we do a `make clean` in our tests before we upload the helm index 🤦‍♂ 

We need to download the helm index in our tests later in CI and write tests to ensure we don't do this again by accident.

Also, since CI always begins with a clean state, we really don't need the `make clean` target invoked.

**Comment by kdorosh** [comment]
Leaving open until we write some tests to ensure this can't happen again if we accidentally decide to add `make clean` to any part of our CI again.

**Comment by rickducott** [comment]
How would you approach testing for this? +1 to the idea, just curious what you intend. 

I would recommend not using `make clean` in CI, especially inside of test code, since it is way too much of a hammer for any particular use case. I think here we just wanted to clear out the generated files inside of the install directory, which would have avoided this problem.

**Comment by kdorosh** [comment]
@rickducott something in the make target that would fail if it tries to upload a helm repo index that is not one larger than the currently hosted one
