### ISSUE TITLE
`ResourceRef` without a namespace

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1929]
ability to provide ResourceRef without providing a namespace - should default to the namespace of the referencing object
* this behavior can be made forced/default for certain fields such as secret refs (increased security, @yuval-k )

**Comment by texascloud** [comment]
I've been using some changes by @ilackarms which implements this for at least routes which refer to upstreams without needing to specify the namespace of the upstream. So far works well!

However the routes part isn't incredibly useful due to other issues and how I am trying to use Gloo with k8s

unfortunately due to https://github.com/solo-io/gloo/blob/048b6f247e5306518a0d34bb522e5ea2fb29831f/projects/gloo/pkg/upstreams/kubernetes/conversions.go#L19 I cannot have a referenced upstream use the route’s namespace if not specified

the reason is due to:
- not specifying serviceNamespace in the kube field of a a manually created Upstream causes the Upstream to be created incorrectly and therefore not usable
- if I let the discovery service create the Upstream via the kubernetes plugin, it creates it in a single namespace that you can modify in Settings, and it doesn’t seem very clear how to say “hey, if the namespace of the Upstream you’re referencing is not specified, look in the namespace of where the discovery service is creating discovered Upstreams”. That seems non-intuitive

So I’m pondering a solution which lets Upstreams/routes be created without needing to parameterize the namespace value inside the Spec of whatever top-level CR we’re creating (Upstream, VirtualService, etc)
