### ISSUE TITLE
Support Tolerations and NodeSelectors on other Deployments

### ISSUE THREAD

**Issue by MikeSouza** [solo-io/gloo#1995]
**Is your feature request related to a problem? Please describe.**

Currently, only the gateway proxies can be configured via Helm with tolerations and nodeSelectors to allow us to schedule envoy on the node pools of our choosing. The discovery, gloo, and gateway deployments do not support this.

**Describe the solution you'd like**

The ability to specify tolerations and nodeSelectors for discovery, goo, and gateway deployments via Helm.

**Describe alternatives you've considered**

N/A

**Additional context**

We would like finer control over the scheduling of ALL the various Gloo pod resources to, for example, an operations node pool separate from our worker node pool where we deploy applications to.

**Comment by kdorosh** [comment]
Another workaround is to leverage kustomize for any helm customizations you'd like to make to our chart until we have a chance to expose every setting that's requested. For more, read here: https://docs.solo.io/gloo/latest/installation/gateway/kubernetes/helm_advanced/

**Comment by ericnelson** [comment]
this is especially important for those of us running mixed agent pool clusters (linux/windows). without the ability to fully control all deployments k8 will attempt to schedule various gloo deployments on the windows nodes :( 
I got around this , at least for testing by using the --dry-run switch from glooctl to generate the yaml and adding nodeSelector sections to all the deployments. Hack yes, but otherwise gloo is a non starter for us.

**Comment by jameshbarton** [comment]
A user needs support for taints in addition to tolerations with Helm.
