### ISSUE TITLE
Add Schema to Gloo CRDs

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2108]

**Comment by EItanya** [comment]
Mostly completed here: https://github.com/solo-io/solo-kit/pull/213

**Comment by jack0** [comment]
The helm chart gloo CRDs are on `apiextensions.k8s.io/v1beta1` so `spec.preserveUnknownFields` is set to `true`. Therefore pruning is not enabled and users can store arbitrary data. This creates problems because if a user incorrectly defines a field in a VirtualService or Upstream object that is unknown, the gloo will crash loop with a fatal error: `error in setup: starting snapshot watch: initial Upstream list: 1 error occurred:\n\t* converting output crd: reading crd spec on resource xxxxx in namespace yyy into v1Upstream: unknown fiend \"mybadfield\" in kubernetes.UpstreamSpec\n\n"`. Defining an OpenAPI schema in the CRDs as well as setting `spec.preserveUnknownFields: false` will fix this issue.

**Comment by kdorosh** [comment]
Thanks @jack0 , that is our plan and we have recently begun work again to add this to our CRDs.

fyi @sam-heilbron ^

**Comment by jack0** [comment]
appreciate the fast response and more appreciative that you guys are working on this. thanks @kdorosh!

**Comment by jack0** [comment]
do we have an ETA for adding schema schemas to the CRDs?

**Comment by kdorosh** [comment]
It was briefly put on hold, but work is ongoing again @sam-heilbron . We hope to have this in a 1.8 beta within the next two weeks
