### ISSUE TITLE
Improve dev UX and iteration of transformation templates

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2114]
We should publish envoy from a library, then invoke it from gloo & glooctl to detect invalid templates at apply time.

**Comment by kdorosh** [comment]
`glooctl validate -f <<< VS yaml`

**Comment by yuval-k** [comment]
note that you can run envoy in validation mode, to only validate configuration.

**Comment by bdecoste** [comment]
1) to be able to output the corresponding proxy object
2) provide both the envoy errors (e.g. cluster)  and gloo errors (e.g. upstream)
3) Be able to provide a proxy object and some delta yaml (change to a virtual object) and validate the new proxy object
4) point validate at an existing env and pull the proxy object from there and apply a delta (e.g. modified virtual service) and validate the resulting new config
5) if there is a way to expose a gloo api that does this instead of via glooctl (to call from ci/cd)

**Comment by kdorosh** [comment]
After the first iteration of this feature, as implemented in https://github.com/solo-io/gloo/pull/2827, user feedback has been generally positive. An additional request has been to include more context about which route and parent resource contained the transformation that had the failed inja template.

A sample error contains:
```
Failed to parse response template: Failed to parse " +
				"header template ':status': [inja.exception.parser_error] expected statement close, got '%'
```
It would be nice if this were wrapped in the resource/route it came from. We have access to the envoy route information when we do the [validation](https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/plugins/transformation/plugin.go#L85) (via `VirtualHostParams` and `RouteParams`) so should be an easy fix to add the envoy route name.

**Comment by bdecoste** [comment]
Need to decouple the helm chart to set alwaysAccept: false but not deploy the validatingwebhook

**Comment by kdorosh** [comment]
@bdecoste w.r.t. https://github.com/solo-io/gloo/issues/2114#issuecomment-634880971 , hasn't this already been addressed in https://github.com/solo-io/gloo/pull/3018 and https://github.com/solo-io/gloo/pull/3017 ?

**Comment by kdorosh** [comment]
validation webhook now handles transformation config
