### ISSUE TITLE
tracing / logging for a particular envoy request

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2117]

**Comment by rickducott** [comment]
I looked into this, it's really frustrating to work with the envoy application logs:
* Envoy is considering adding support to surface the connection and stream id in the response, but right now it needs to be deduced from the logs by matching against something in the request
* Parsing all the envoy logs related to the request is annoying because some logs span multiple lines with line breaks. This can be changed by passing different options to the bootstrap config to escape logs
* Ultimately, the data that is logged to envoy is hit or miss

Would love a better story here, but not clear what that looks like. Access logging has been a more straightforward way to record request, routing decision, and response
