### ISSUE TITLE
Incorrect VaultSecretSource address causes discovery & gloo pods to CrashLoopBackOff

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2194]
```
  vaultSecretSource:
    address: http://1.2.3.4:8200
    token: root
```
`
{"level":"fatal","ts":1579022703.2057452,"logger":"gloo-ee","caller":"setuputils/main_setup.go:99","msg":"error in setup: starting snapshot watch: initial Secret list: reading namespace root: listing directory secret/metadata/gloo/gloo.solo.io/v1/Secret/: Get http://1.2.3.4:8200/v1/secret/metadata/gloo/gloo.solo.io/v1/Secret?list=true: dial tcp 1.2.3.4:8200: connect: connection refused","version":"undefined","stacktrace":"github.com/solo-io/gloo/pkg/utils/setuputils.Main\n\t/workspace/gopath/pkg/mod/github.com/solo-io/gloo@v1.2.12/pkg/utils/setuputils/main_setup.go:99\ngithub.com/solo-io/solo-projects/projects/gloo/pkg/setup.Main\n\t/workspace/gopath/src/github.com/solo-io/solo-projects/projects/gloo/pkg/setup/setup.go:40\nmain.main\n\t/workspace/gopath/src/github.com/solo-io/solo-projects/projects/gloo/cmd/main.go:11\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}`

**Comment by rickducott** [comment]
I'm not sure what the desired behavior here is, because Gloo can't really function without a view of the secrets, so this does seem to be a fatal error. Since I am aggressively closing out issues in the backlog, going to close this since it's not clear to me what alternative we should go with. Please reopen if you feel I am mistaken.
