### ISSUE TITLE
Update Custom Extauth example to show how to use context extensions

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2266]
https://docs.solo.io/gloo/latest/security/auth/custom_auth/

We should demonstrate how to configure reading info passed from context extensions in this tutorial, has tripped up users in the past

**Comment by kdorosh** [comment]
Context extensions are not available on the full custom auth implementation, and are only available on the gRPC interface for extauth. We should update our generated docs from API to be clearer about this: https://docs.solo.io/gloo/latest/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#customauth

**Comment by tayvs** [comment]
@kdorosh When I tried to write custom auth, that article were very useful especially code example. It's would be nice to have such example in doc because server response format is pretty tricky.

https://medium.com/google-cloud/envoy-external-authorization-server-envoy-ext-authz-helloworld-82eedc7f8122
