### ISSUE TITLE
document how to expose gloo dashboard via gateway

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2345]

**Comment by rickducott** [comment]
I think we could include a few helm chart values to more easily deploy the UI behind Gloo. It's a bit annoying because it interacts with other features -- do you expose it with SSL? are you running discovery or do you need the upstream to exist? what domain are you using? For this reason, I tend to manage these resources myself, rather than wish they were packaged in the chart. 

We've also received some feedback from users that they want to expose this separately, though other users have wanted similar functionality. Ultimately, feels more like a docs issue rather than a feature.

**Comment by artberger** [comment]
duplicate of https://github.com/solo-io/gloo-mesh-enterprise/issues/3391
