### ISSUE TITLE
Support Consul service registry integration when Consul service endpoints are hostnames not IPs

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2424]
Options discussed:

1) Have Gloo EDS resolve hostnames and provide Envoy with the required IPs
2) Expose Envoy's custom resolver and other necessary config to replace EDS with STRICT_DNS and Consul as the resolver. 

This feature needs to work with https://github.com/solo-io/gloo/issues/2308

**Comment by kdorosh** [comment]
the leading option is to expose strict_dns and a custom resolver (which would be consul in this case).

**Comment by kdorosh** [comment]
based on https://github.com/envoyproxy/go-control-plane/issues/87#issuecomment-400739949 , sounds like using a custom resolver in EDS is not an option.

**Comment by kdorosh** [comment]
appears that registering a custom resolver is not supported, so we will resolve hostnames in the control plane as suggested here: https://github.com/envoyproxy/go-control-plane/issues/87#issuecomment-400739949

**Comment by kdorosh** [comment]
moved onto having Gloo resolve hostnames before adding to EDS cache because:
- custom resolver must be an IP, cannot be a hostname itself
- will not work to resolve if a service is backed by several endpoints, and envoy may treat cluster assignments as new each time the contents change, which would affect membership and cluster warming
