### ISSUE TITLE
external-dns: support Gloo Gateway as a DNS Endpoint Source

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2467]
Today Gloo users have to decide between the `gateway` API and `ingress` API for routing. Gateway exposes the full set of Envoy features, but `ingress` integrates natively with `external-dns`: https://github.com/kubernetes-sigs/external-dns/ which automates DNS provisioning from Kube resources.

We should contribute a plugin upstream for Gloo (Istio and Contour are already supported) which allows External-DNS controller to process DNS Endpoints from Gloo Gateways+VirtualServices

More info on "Sources":

https://github.com/kubernetes-sigs/external-dns/blob/master/docs/contributing/sources-and-providers.md

**Comment by cten** [comment]
This would be great, we are looking to use Gloo for handling native Ingress resources and as a Gateway. We currently use External-DNS to dynamically update DNS records as new services are deployed. It appears that the Ingress scenario might already be handled because Gloo sets the status field in Ingress objects but being able to also support the VirtualServices would be awesome allowing us to take advantage of our External-DNS deployment for all domains.

**Comment by ilackarms** [comment]
to track on external-dns: https://github.com/kubernetes-sigs/external-dns/issues/1435

**Comment by base698** [comment]
Would also really like this feature.

**Comment by jameshbarton** [comment]
Another enterprise customer asked for this to help with integrating Edge with a large (~150), mission-critical service network that supports their entire customer digital experience. See details in internal notes.
