### ISSUE TITLE
Allow chaining of upstream calls

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#2601]
A useful feature of Gloo would be the ability to "chain" upstream calls, allowing for a set of upstreams to be requested sequentially.

A potential use case for this is to satisfy the need to call a prerequisite service (or multiple) before calling the "primary" service. This can be seen as a more generic "extauth" flow for non-auth use cases.

**Comment by yuval-k** [comment]
do you have a s use case in mind?
I'm asking as a generic synchronous upstream call before every request reminds me of mixer a bit. istio had issues with this approach. the main problem they experienced as I understand it, is that for this kind of service to be useful it needs a lot of context form envoy, as envoy doesnt  know what mixer needs ahead of time, send sent a lot of data to mixer leading to cpu usage and latency.

The alternative solution is webassembly for custom extensions in the data plane

**Comment by rickducott** [comment]
The customer who requested this is trying to figure out how to bring new services online behind the gateway. The business wants the gateway to perform an additional authorization check, where the proxy asks an internal quota service for authorization. The platform team would prefer to keep this logic out of the core auth service, and for this to be a discrete round trip from the gateway to the quota service. A few details about the quota service:
- The computation it does is complex, not guaranteed to be precise (quota is just an estimation)
- Can be slow, added latency is an acceptable tradeoff and preferred to keep the concerns separate
- Unclear but likely should be modeled like auth (fail closed) instead of rate limit (fail open)

Regarding the concern about mixer, we had discussed the performance concern directly and it sounded like the preferred tradeoff for this specific case.

**Comment by yuval-k** [comment]
makes since; this can probably be done by adding extauth multiple times to the filter chain
