### ISSUE TITLE
How to pass Consul Certificates for TLS Encrypted Communication in K8s to Gloo

### ISSUE THREAD

**Issue by xbaun** [solo-io/gloo#2666]
I need to connect to a consul cluster outside of K8s which uses TLS encryption. The current helm chart doesn't allow me to configure a custom volume (config-map) which holds the certificates for `caFile`, `certFile` and `keyFile` in [api/v1/settings.proto](https://docs.solo.io/gloo/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk/#consulconfiguration) (at least i didn't found any matching helm value or template block within the chart).

Is consul TLS Encryption currently supported for K8s helm chart?

**Comment by rickducott** [comment]
It looks like we don't currently support it in our helm template: https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/18-settings.yaml

This would be a fairly simple contribution if you are interested in taking a stab at it! Let us know and we can help. Otherwise, we'll try to batch up a handful of helm issues like this and work through them as soon as we can.

**Comment by kdorosh** [comment]
Another workaround is to leverage kustomize for any helm customizations you'd like to make to our chart until we have a chance to expose every setting that's requested. For more, read here: https://docs.solo.io/gloo/latest/installation/gateway/kubernetes/helm_advanced/
