### ISSUE TITLE
AWS EKS Service Accounts

### ISSUE THREAD

**Issue by RichiCoder1** [solo-io/gloo#2698]
Request: Can Gloo support using [IAM Role support for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) when running in EKS in leu of secrets? For example, for when using EC2 upstreams.

**Comment by rickducott** [comment]
I'm going to mark this as an enhancement, as I believe the secret is currently required on the EC2 upstream.

**Comment by yuval-k** [comment]
i think this is already supported, from the docs:

> Optional, if not set, Gloo will try to use the default AWS secret specified by environment variables.

in the code you can see that with no secret ref, the default session is used:
https://github.com/solo-io/gloo/blob/7f07c6b0d98d63da95104022c4da5124af8f2508/projects/gloo/pkg/utils/aws/session.go#L27

similar thing applies to the aws lambda support.

@RichiCoder1 do you have a different experience?

**Comment by RichiCoder1** [comment]
I've not tried yet. Was asking because the documentation made it appear that ref was required, and not clear what would happen if you left it off.

**Comment by RichiCoder1** [comment]
Looking over that code and the sdk docs, it does look like Gloo would do the right thing though! I'd maybe make this a request to update the docs.

**Comment by ned1313** [comment]
From what I can tell, it would be supported to use the instance profile of the worker node, but not a service account. The Gloo and Gateway pods would not be associated with the service account, and therefore would not have the proper environment variables to authenticate. The deployment for the pods would need to be updated to include the services account, and then the pods would need to be re-launched. I will update the docs to reflect this, but I think using service accounts would require an application enhancement to Gloo.

**Comment by RichiCoder1** [comment]
Ahh, that's true! Gloo's helm chart sets up service accounts, but doesn't allow setting annotations which would be a blocker.

**Comment by lgadban** [comment]
Seems like the outstanding work for this to work are:

- [ ] decide which `ServiceAccount` would own this interaction (i.e. control-plane or data-plane)
- [ ] allow for annotating the `ServiceAccount` (could also be accomplished via `kustomize`)
- [ ] ensure that the AWS identity/role environment variables are used to retrieve AWS Role credentials

Additionally, since the credentials returned will consist of an access key ID, a secret access key, and a security token, work will need to be done to support the session/security token (https://github.com/solo-io/gloo/issues/2373) when signing requests, e.g. making a Lambda call.
