### ISSUE TITLE
Remove warning around route table weights

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2793]
After a post/webinar on canary rollout, an OS user asked me for a follow up that better models how they use gloo - with an ops team responsible for the domain and VS, and dev teams owning their own route tables. In order to make this self-service, they use a generic selector in the virtual service. However, this makes it awkward to avoid warnings in Gloo, because either teams need to pick an arbitrary weight on their route table that is unique compared to other teams, or gloo will warn you that the ordering may be unexpected. In this scenario, it makes sense to turn off this warning, ideally with a setting that persists. Otherwise, `glooctl check` will exit with a status code `1` and it's hard to use that in other automation.  

Here's a deeper guide explaining the scenario: https://github.com/solo-io/gloo-ref-arch/tree/master/two-phased-canary/part2

**Comment by lgadban** [comment]
Since `glooctl check` will short-circuit and error out when it hits this issue (or any other issue), this warning will prevent `glooctl check` from checking the subsequent resources: `Gateways` and `Proxies`. This can result in major problems that `glooctl check` could normally detect being hidden from the user, especially given that quite a few users will run into this while upgrading from 1.2.x to 1.3.x

I think coming up with a plan for a sane way to handle warnings, such as the route table weights, in `glooctl check` is important, however I also think there is a usability win by not short-circuiting when an issue has been encountered by `glooctl check` and making a best effort to validate all resources. This might be worth tracking a different issue.

**Comment by rickducott** [comment]
I filed the enhancements of reporting all errors, not just stopping at the first one, in #2952

**Comment by rickducott** [comment]
After discussing further with @marcogschmidt @bdecoste @lgadban @kdorosh we concluded this warning doesn't make sense, it is the default behavior and weights aren't needed most of the time. So we'll resolve this issue by removing the warning about weights.
