### ISSUE TITLE
Move to v3 Envoy xDS APIs

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#2815]
We are still using v2 of the Envoy `go-control-plane` xDS APIs. We should switch to v3 APIs as Envoy is [planning on rejecting v2 xDS APIs starting in Q3 of this year](https://github.com/envoyproxy/envoy/issues/10816).

**Comment by yuval-k** [comment]
note that the transition can be gradual, as currently you can mix v2 and v3

**Comment by kdorosh** [comment]
Steps:
- [ ] Move HCM and lower config to v3
- [ ] Support v2 and v3 versions of top-level resources over XDS (i.e., clusters, listeners, etc.) by translating between v2 and v3 versions of top-level resources in-memory
- [ ] Write a doc/guide explaining the rolling upgrade guide for Gloo and breaking envoy changes between v2 and v3

**Comment by arianaw66** [comment]
Since I'll be passing this work on to someone else's, here are a few things from my notes that could be useful:

PRs:
- Part 1- hcm https://github.com/solo-io/gloo/pull/3233
- Tangent PR- wellknown https://github.com/solo-io/gloo/pull/3240
- Part 2- tcp https://github.com/solo-io/gloo/pull/3267
- Part 3- non-top-level in plugins https://github.com/solo-io/gloo/pull/3275
- Solo-projects first PR- pull in new upgrades in gloo repo https://github.com/solo-io/solo-projects/pull/1794
- Solo-projects Part 1- non-top-level in plugins https://github.com/solo-io/solo-projects/pull/1802
- Upgrade bootstrap config https://github.com/solo-io/gloo/pull/3343
- Envoy-operator upgrade bootstrap https://github.com/solo-io/envoy-operator/pull/12
- Part 4- outside projects/gloo https://github.com/solo-io/gloo/pull/3302
- Replace deprecated Cluster.hosts https://github.com/solo-io/gloo/pull/3414
- Solo-projects upgrade bootstrap https://github.com/solo-io/solo-projects/pull/1810

Old PRs from abandoned approach:
- Part 1- upgrade route package: https://github.com/solo-io/gloo/pull/3110
- Part 2- upgrade listener package: https://github.com/solo-io/gloo/pull/3177
- Sds fix to accomodate v2 and v3 (Eitan’s): https://github.com/solo-io/gloo/pull/3192
- Part 3- upgrade cluster package/get rid of envoyapi package: https://github.com/solo-io/gloo/pull/3196
- ? Ads (Eitan’s- unmerged): https://github.com/solo-io/gloo/pull/3199

Diff from abandoned approach since it’s come in very handy: https://github.com/solo-io/gloo/compare/feature-envoy-v3-migration

Things to check to ensure this is complete:
- `grep -nr "github.com/envoyproxy/go-control-plane/envoy/type" .` includes v3 everywhere
- `grep -nr "go-control-plane/.*v2.*" .` is empty
- no imports called “envoyapi” because it should all be more specific now, like envoycluster or envoylistener in many cases (`grep -nr "\"github\.com/envoyproxy/go-control-plane/envoy/api/v2\"" .`)
- `go build projects/gloo/cmd/main.go` should work, as should other pods
- projects/gloo/pkg/plugins/plugin_interface.go file should have same number of implementations now as it does on master. This ensures every intended implementation is actually the right type still.
- Don’t include these deprecated envoy names anywhere: https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.14.0.html#deprecated
- Nothing with “HiddenEnvoyDeprecated” prefix
- Nothing deprecated? (Code -> Run Inspection By Name -> type “Deprecated”)
- TODOs
- No ptypes.MarshalAny (it’s bad, use MessageToAny instead)

Imports that are still used in v3:
- "github.com/envoyproxy/go-control-plane/pkg/cache/types"

To find new envoy package, for example: `grep -nr "type HttpGrpcAccessLogConfig " /Users/{your-user}/go/pkg/mod/github.com/envoyproxy/go-control-plane@v0.9.6-0.20200529035633-fc42e08917e9/envoy/ | grep v3`

TODO:
- other repos: Solo-projects, solo-kit, others?

Relevant links:
- Envoy v2 API reference: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api, v3 API reference: https://www.envoyproxy.io/docs/envoy/latest/api-v3/api
- How Envoy xDS works including how it’s changed and details on functions: https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol, Envoy secret discovery service: https://www.envoyproxy.io/docs/envoy/latest/configuration/security/secret
- For updating configmaps:
    - Gloo docs on Envoy bootstrap https://docs.solo.io/gloo/latest/installation/advanced_configuration/gateway-proxy-config/
    - Envoy bootstrap config overview https://www.envoyproxy.io/docs/envoy/latest/configuration/overview/bootstrap
    - v2 bootstrap proto: https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/bootstrap/v2/bootstrap.proto
    - v3 bootstrap proto: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/bootstrap/v3/bootstrap.proto

**Comment by sam-heilbron** [comment]
This was resolved by the attached PRs
