### ISSUE TITLE
support advanced (i.e. script based) upstream (not envoy itself) health checks

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2837]
implement envoy custom health check?

**Comment by kdorosh** [comment]
The final ask:

Implement _enterprise-only_ advanced HTTP health checking API for envoy. Previously, Gloo supported per-endpoint paths in the HTTP health checking config on static upstreams. After this change we support per-endpoint method configuration of the HTTP health check requests to static upstreams, as well as complex regex json / regex parsing of the HTTP response to make determination on the HTTP health check response (rather than just look at the HTTP status, like upstream envoy). Regex/json parsing of the response can be configured in the `ResponseAssertions` field on the upstream's HTTP health check.
