### ISSUE TITLE
deploying VS before auth config causes invalid proxy that is hard to correct

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2920]
I deployed a virtual service first, then deployed the auth config it referenced. After waiting awhile, `glooctl check` continued to report the missing auth config, and the resulting proxy was accepted but did not have the http listener. When I edited the virtual service (by removing the status field), this did not cause the proxy to be generated correctly, it was stuck. After deleting the proxy, it was recreated correctly and worked as expected.

**Comment by ashleywang1** [comment]
Ah, this is because the AuthConfig is in the Gloo ApiSnapshot, but the VirtualService is in the Gateway ApiSnapshot.
When the AuthConfig is updated, the Gloo pod resyncs, but the Gateway pod doesn't.

I'm not sure that changing the status of a virtual service actually triggers a resync of the gateway pod. Another way to force the Gateway pod to resync would have been to add a vs and delete it. Obviously, that's not ideal.

Of the top of my head, it's also probably not a good idea to add AuthConfigs to the gateway ApiSnapshot, because then we'd have two pods operating on the AuthConfig status. Maybe it might be okay if we're careful.
