### ISSUE TITLE
Gateway fails to recover from transient error state

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#3063]
**Describe the bug**

I updated my virtual services, gateways, and routetables at once using GitOps. No problem. I went from using a single routetable that was explicitly named to using a route table selector to select about a dozen routetables.  Notably, the original route table would NOT match the selector.

When I upgraded, everything was fine, except that a few routes were broken. (I still have to figure that out).  So, I reverted ALL the changes at once using GitOps. That is when my troubles began.

Alarms went off on my production system. I inspected and saw that the new routetables were gone, but the new virtual service was still in K8s.  So I got 404s. 

This is not desirable, but understandable given my use of route table selectors.  The gateway has no way of knowing that it is in an inconsistent state. While I could not spend the time to capture the problem (since my production system was affected), I believe that the gateway got into an error state and could not recover. 

I am using `quay.io/solo-io/gateway:1.3.24`. 

N.B. I *have* seen the gateway get into an unrecoverable error state before.  However, in those cases, there was a persistent error in my configuration.   In those instances, I literally have manually restarted the gateway.  In this case, there was only a transient inconsistent state. 

I do not have validation turned on.  Not that that should matter, since the resources individually are valid.

Thank you for your attention to this matter.  It caused some production downtime today for our users, and a bit of anxiety for me. :)

**Comment by kdorosh** [comment]
First off, sorry to hear that you encountered downtime in production with Gloo. Please help us help you so this never happens again.

> In this case, there was only a transient inconsistent state.

Can you clarify what you meant by this?

Based on the description, it sounds like Gloo got into a bad state once you reverted the route table selector (based on "While I could not spend the time to capture the problem (since my production system was affected), I believe that the gateway got into an error state and could not recover.") and you took manual action to fix it. What was that manual action?

If there was no manual action, how long was the downtime / how long did Gloo take to correct its configuration.

Additionally, can you provide scrubbed logs or send us some privately from the event? I would love to see the gateway and gloo logs before and after the route table changes, as well as when you reverted.

Thanks @derrickburns

**Comment by derrickburns** [comment]
Thanks @kdorosh.  I will try to reproduce this when I can.   Then, I can give you more actionable data.
