### ISSUE TITLE
Help point documentation search results to newer versions of docs

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3092]
**Describe the requested changes**
While searching for gloo docs in e.g. google, quite of a few of the results are indexed to older versions of the docs. Some form of SEO should be added to help reduce indexing of the older versions of the docs.

**Link to any relevant existing docs**
Some examples:
https://www.google.com/search?client=firefox-b-1-d&q=gloo+aws+upstream
https://www.google.com/search?q=gloo+rate+limiting&oq=gloo+rate+limiting

**Additional context**
One option is to add canonical URLs to the docs (including older versions) to always point at the 'latest' docs.

**Comment by Sodman** [comment]
We should also consider adding some kind of banner or notice to the top of the docs for older versions of gloo, so that if users _do_ accidentally find their way to older versions, it should be obvious that it's out of date and have a link to newer versions.

Istio has a [subtle change](https://istio.io/v1.5/docs/concepts/what-is-istio/) where they change "Istio" to "Istioldie":
![image](https://user-images.githubusercontent.com/1928125/84519796-8f786b80-aca0-11ea-9a65-3db75317d7ca.png)

ElasticSearch has a [much more obvious banner](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-aggregations-bucket-composite-aggregation.html) explaining how to get to the new docs:
![image](https://user-images.githubusercontent.com/1928125/84520064-f39b2f80-aca0-11ea-82b9-ee1d8650cc61.png)

My preference would be for the latter style, as it would seriously cut down on users accidentally following older docs and running into compatibility issues.

**Comment by ned1313** [comment]
I have updated the older docs images with marked text at the top of each page like this:
<img width="1418" alt="Screen Shot 2020-10-21 at 9 29 42 AM" src="https://user-images.githubusercontent.com/6720613/96733105-1512d300-1387-11eb-93b1-1c0680984a61.png">

And I have added a robots.txt file to stop search engines from crawling the older sites.
