### ISSUE TITLE
Create a dedicated repository for Gloo APIs

### ISSUE THREAD

**Issue by joekelley** [solo-io/gloo#3127]
**Is your feature request related to a problem? Please describe.**
When developing new projects on top of the Gloo API today, it's necessary to import directly from the Gloo repository. Internal dependencies such as go-utils and solo-kit also get pulled in, along with much of the Kubernetes API. This leads to conflicts on transitive dependencies and a lot of unnecessary complexity compared to a standard client-go API.

**Describe the solution you'd like**
Solo.io should maintain a Gloo API repo separately from the Gloo repo itself. The API repo will store a mirror of the protobuf APIs in the Gloo repo as well as the kube types and clients needed to develop controllers atop the Gloo API.

To keep the Gloo development process as simple as possible, Gloo developers will continue to commit API changes directly to this repository. When API changes are committed to master in this repo, a CI job will push the corresponding changes to the external API repo. The job will be responsible for transforming Gloo protos such that they can be used with [skv2's](https://github.com/solo-io/skv2) code generation, which is [controller runtime](https://github.com/kubernetes-sigs/controller-runtime) compatible.

**Comment by mhofstetter** [comment]
If I'm getting it right https://github.com/solo-io/solo-apis is the very promising result / work in progress for this ticket.

I tested it and it seems to fit the requirements!

Feedback:
1. It would be great if the dependency to github.com/solo-io/solo-kit` would be gone completely since skv2 is the successor

-> `ResourceRef` is still only available in `github.com/solo-io/solo-kit/pkg/api/v1/resources/core` which is needed to reference various objects (e.g. Upstream)

2. It would be great if there's a proper API to easily define a "GlooSecret" programatically which is necessary to define the rootCa for ingress mTLS.

-> Defining only TLS on the Virtualservice can be done by defining a plain Kubernetes TLS secret. To configure mTLS (define rootCA) it's necessary to "construct" and provide a "gloo secret" which we currently build by using the function `MapStringInterfaceToMapStringString` (like it's been done by glooctl -> https://github.com/solo-io/solo-kit/blob/f300a3f30ddf5fdcb1515b387359d53643c2bb4a/pkg/api/v1/clients/kubesecret/resource_client.go#L81) .

This is quite messy - either we need to "inline" this in our code our you provide a way to easily create such a secret via skv2.

3. It would be great if the dependency to `github.com/solo-io/go-utils` would be gone, as this still results in dependencies to Helm & docker

-> Vendoring pulls in docker dependencies

```
go mod vendor
go: github.com/solo-io/solo-apis@v0.0.0-20200807174746-9ea7dfeef2cb requires
        github.com/solo-io/go-utils@v0.16.5 requires
        helm.sh/helm/v3@v3.0.0 requires
        github.com/deislabs/oras@v0.7.0 requires
        github.com/docker/docker@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

This can be solved with the following entry in the `go.mod` but it would be great if this wouldn't be necessary.

```
replace github.com/docker/docker => github.com/moby/moby v0.7.3-0.20190826074503-38ab9da00309
```

I thought it's best to provide the feedback in this issue & repo because i didn't want to spread it over all the repos. maybe you already addressed some parts of this internally.

@marcogschmidt @ashleywang1 @EItanya

**Comment by EItanya** [comment]
@mhofstetter thanks for the feedback. 

Removing the `solo-kit` dependency is definitely something we're looking to do. In fact most of the work is already done in this other [PR](https://github.com/solo-io/skv2/pull/24). The `collector` is the only component that needs to be moved.

Removing `go-utils` will be a little harder, but I see your point, and we can definitely look into it. There is a lot of bloat in there, and we are most likely only using a couple of functions in `skv2`.

Also, `GlooSecret` secret functions is definitely an interesting idea. The original idea for `solo-apis` was simply a home for the APIs, but I could definitely see good reason to include helper code for the secrets as well.

**Comment by ashleywang1** [comment]
Closing as `solo-apis` is the repo for this. Any subsequent tickets for this should be filed in that repo.
