### ISSUE TITLE
Broken Links in Gateway.proto docs

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3421]
**Describe the requested changes**
Most of the links on the https://docs.solo.io/gloo/latest/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/gateway.proto.sk page are broken

**Link to any relevant existing docs**
https://docs.solo.io/gloo/latest/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/gateway.proto.sk

**Browser Information**
N/A

**Additional context**
N/A

**Comment by jehawley** [comment]
All links seem to work on the most recent docs version in Chrome and Firefox. Only able to reproduce where I was investigating the issue before the most recent docs release; I assume this is due to a cached bad version of the page.

**Comment by jehawley** [comment]
Was able to reproduce both success and failure. It may make a difference whether the user navigates to the page from the docs homepage vs clicking on the direct link.

**Comment by jehawley** [comment]
The issue is a missing trailing '/'. So https://docs.solo.io/gloo/latest/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/gateway.proto.sk should consistently have bad links and https://docs.solo.io/gloo/latest/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/gateway.proto.sk/ should consistently have good links. This behavior is not intuitive and we should probably redirect one to the other / take down one of the pages.

**Comment by jehawley** [comment]
Putting this ticket on hold until after our docs cluster upgrade.

**Comment by arianaw66** [comment]
Dropping a quick link to the PR where I removed the default column from the docs in case it's helpful: https://github.com/solo-io/solo-kit/pull/376/commits/222ddc7ff0cd62249219a01be4d6754e30db3587
