### ISSUE TITLE
include defaults for all config options (e.g. jwt.provider.keepToken)

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3478]
**Describe the requested changes**
Dosc do not include defaults for all config options

**Link to any relevant existing docs**
For example, https://docs.solo.io/gloo/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/jwt/jwt.proto.sk/#vhostextension

does not specify the default for keepToken.

**Comment by arianaw66** [comment]
The default for a given field will only show up if [the FieldDescriptorProto's DefaultValue field](https://github.com/gogo/protobuf/blob/v1.3.1/protoc-gen-gogo/descriptor/descriptor.pb.go#L812) is populated, as defined in [our template](https://github.com/solo-io/solo-kit/blob/v0.13.11/pkg/code-generator/docgen/templates/markdown/proto_file_template.go#L69).
An example of the syntax for populating this field in the proto file can be seen [here](https://github.com/gogo/protobuf/blob/v1.3.1/protobuf/google/protobuf/descriptor.proto#L590).

I don't currently see a way to programmatically fill in this field.
We can either add the default for every field in our protos, or we can remove the DEFAULT column from the docs all together, since it's rarely populated anyway, and the DESCRIPTION column often states what the default value is.

**Comment by arianaw66** [comment]
(We decided to remove the default column. This issue will be resolved when the solo-kit changes are pulled into gloo.)

**Comment by arianaw66** [comment]
Whoops, had a typo in `resolvesIssue` lol.
