### ISSUE TITLE
Need documentation/repo for gloo E helm chart

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3679]
**Describe the requested changes**
The values for the GlooE chart are not documented somewhere externally as the chart is private.
This makes it more difficult to understand which values are available for customization.
There should be a reference doc for the GlooE values.

**Link to any relevant existing docs**
N/A

**Additional context**
It would also be nice if we could find a way to expose the GlooE chart

**Comment by jameshbarton** [comment]
Need for this was emphasized in a recent new-user interaction. They were looking for a way to disable apiServer and landed [here](https://docs.solo.io/gloo/latest/installation/enterprise/#list-of-gloo-helm-chart-values). They first tried to use `apiServer.enterprise` because it was the only `apiServer` value listed, but eventually figured out after much sleuthing to use `apiServer.enable` instead.  It would have been better if all values had been listed.

(It would also be good if we standardized on `enabled` as the only proper suffix for feature enabling. That caused the same user some temporary problems as well.)

**Comment by kdorosh** [comment]
reopening until open source changes are merged
