### ISSUE TITLE
Glooctl prompts me to "upgrade" to a version older than I have

### ISSUE THREAD

**Issue by kkapelon** [solo-io/gloo#4037]
**Describe the bug**
Glooctl says that I should upgrade to 1.5.14 even though I am using 1.6.0-beta25

```
$glooctl ui
----------
glooctl binary version (1.6.0-beta25) differs from server components (v1.5.14) by at least a minor version.
Consider running:
glooctl upgrade --release=v1.5.14
```

**To Reproduce**
1. Download latest glooctl-linux-amd64 from releases. Rename to glooctl and make it executable.
2. Install gloo with `glooctl install gateway --with-admin-console`
3. Run `glooctl ui` to see the dashboard

**Expected behavior**
Either Gloo should detect that 1.6.0-beta-beta25 is higher than 1.5.14 and say nothing, or at least print a warning. The suggestion to "upgrade" to an older version should not be printed

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version: 1.6.0-beta25
- Kubernetes version: GKE 1.16

**Comment by Sodman** [comment]
Hi @kkapelon, thanks for the well written issue, we very much appreciate the repro steps.

There's actually a few different things going on here:
- When you install `--with-admin-console`, we get the admin console components of Gloo Edge from the Gloo Edge Enterprise helm chart, so we must use the Gloo Edge Enterprise version
- Unless otherwise specified, this will default to the latest _stable_ Enterprise release version, which right now is `1.5.14`.
- The warning you're seeing is triggered when the CLI version and the server version differ by at least one minor version. You're seeing it here because the server is running 1.5.14, and the CLI is running 1.6.0-beta25
- The upgrade message is a little confusing, because `glooctl upgrade` can actually be used to update the CLI to any version. In practice people almost always update to newer versions, but you can use it to go back to earlier versions, too.

To override the default "stable" enterprise release version when installing, you can provide the latest (Enterprise) version (which can be grabbed from our [enterprise helm repo](https://storage.googleapis.com/gloo-ee-helm), currently v1.6.0-beta13) to the installer when installing with the console, for example to install the latest as of today, you can run:

```
glooctl install gateway --with-admin-console --version v1.6.0-beta13
```

**Comment by kkapelon** [comment]
Thanks for the clarification.

However I didn't see the `--version` option here https://docs.solo.io/gloo-edge/latest/reference/cli/glooctl_install/
How do you want me to proceed? Close this issue and open another one for the docs? Leave this open?

Also as a suggestion maybe rename `glooctl upgrade` to `glooctl set-version` or something similar?

**Comment by Sodman** [comment]
In terms of the docs, I believe you'll need to go one level deeper, to the `gateway` subcommand - https://docs.solo.io/gloo-edge/latest/reference/cli/glooctl_install_gateway/ to see the `--version` option

Normally I'd be all for adding at least an alias to the command to make it clearer, but given the use case here it could be tricky as older versions obviously won't have any new commands we add. The scenario I'm thinking of as an example would be:

1. Download latest version, get 1.6.0-beta26 with a new 'set-version' feature
1. Realize you actually wanted 1.5.0 stable, so you do a `glooctl set-version v1.5.0`
1. Now that you're on `1.5.0`, you don't have the `set-version` feature anymore, so any changes (either upgrades or downgrades) will need to use the old `glooctl upgrade` command

@kdorosh do you have any strong thoughts on this? Specifically adding an alias for `glooctl upgrade` to something more clearly bi-directional (or we could add a 'downgrade' that's functionally equivalent perhaps)? I'm thinking maybe we just add better documentation clarifying how to switch between glooctl versions somewhere around [here](https://docs.solo.io/gloo-edge/latest/installation/preparation/)?

**Comment by kdorosh** [comment]
I agree that the current name can be misleading, would support adding another alias. I wouldn't recommend removing the old one from `glooctl` until we are considering a Gloo Edge 2.0, however.

Separately, while doing the alias I'd like the new one to make it clearer that the command is used to upgrade the `glooctl` binary itself, rather than the server components (akin to `helm upgrade`). Perhaps `glooctl binary set-version`?
