### ISSUE TITLE
Docs search crashes on occassion - especially on weaker machines

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#4093]
**Describe the requested changes**
Using the search bar on our docs can crash the page occasionally https://docs.solo.io/gloo-edge/latest/

**Browser Information**
I'm able to reproduce reliably on Brave, although I don't think the problem is browser-specific.

**Additional context**
We should do a design doc so other Soloists can reuse our solution. We should first investigate either:
- trimming search
- disabling search
So the page can no longer crash. Second to that, we should investigate longer term solutions such as more pre-computations, or replacing with backend search tools.

**Comment by Sodman** [comment]
For context:

Today the search is powered by [lunrJS](https://lunrjs.com/)

The lunr index is currently constructed at build-time, based on the Hugo index, when we build the Docker image for the docs. This happens here - https://github.com/solo-io/gloo/blob/master/docs/build-docs.sh#L125

This index file (search-index.json) is ~8MB of text (although it's gzipped to ~550kb for over-the-wire transfer). The reason for the index's large size is because all text content on all pages is indexed. Looping over and parsing 8MB of text in JS is understandably causing some performance problems.

One option for drastically reducing the size of this, would be to only index page titles, headers and metadata. This would speed up the search _significantly_, although we'd lose the ability to search for arbitrary strings contained on any given page.

A quick win would be adding a debounce to the search, the code for which is in the hugo theme repo - https://github.com/solo-io/hugo-theme-soloio/blob/master/static/revealjs/plugin/search/search.js#L181-L202

**Comment by sam-heilbron** [comment]
This was resolved by https://github.com/solo-io/hugo-theme-soloio/pull/26 and https://github.com/solo-io/gloo/pull/4116
