### ISSUE TITLE
Create Helm Chart Value for `admin_port_cluster` in `9-gateway-proxy-configmap.yaml`

### ISSUE THREAD

**Issue by cmwylie19** [solo-io/gloo#4159]
**Is your feature request related to a problem? Please describe.**
A client is converting from a deployment to a Daemon Set for their multiple gateway proxies. Since Daemon Sets use `HostPort`, they are facing a port conflict for the value of `admin_port_cluster` on the `gateway-proxy-envoy-config` config map because port 19000 is hardcoded into the helm chart and they already have that port allocated in their environment. 

**Describe the solution you'd like**
To have the `admin_port_cluster` value as a variable in the helm chart.

**Describe alternatives you've considered**
- Using a sed command to substitute 19000 for 19001 and reapply the config map
- Using Kustomize to post render the manifest

The problem with the above solutions is that changing a port could result in unexpected outcomes in logging, observability, and glooctl commands.

**Additional context**
 [Link to the config map in question:](https://github.com/solo-io/gloo/blob/85bb112f9ffb033065992d1a9ac7816a6c54284f/install/helm/gloo/templates/9-gateway-proxy-configmap.yaml#L299)

**Comment by stevenjm** [comment]
Another alternative (that seems to be working for me, although I've only tested it for a couple of minutes) is to not use hostNetwork. hostPort doesn't require hostNetwork, as Kubernetes will just map the host port to the corresponding container port if hostNetwork isn't in use, but this seems to have been configured with hostNetwork from the beginning and it's not clear to me why that is.

This solution also has some security benefit, since a compromised data plane won't have access to the host network.
