### ISSUE TITLE
passthrough auth - support updates to the State

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4297]
Given an AuthConfig CR with 2 steps: passthrough + OPA
If I want to pass some metadata from the passthrough service to OPA
Then, I would like to be able to write these metadata to the State

**Comment by sam-heilbron** [comment]
At the moment the PassThrough service can update state to be used by other services. An example of this is here: https://github.com/solo-io/gloo/blob/a120740da160a05db04b21cda9cfb52ba8910382/docs/examples/grpc-passthrough-auth/pkg/auth/v3/auth-with-state.go#L70, and the corresponding documentation is here: https://docs.solo.io/gloo-edge/master/guides/security/auth/extauth/passthrough_auth/#sharing-state-with-other-auth-steps.

As for sharing metadata between passthrough and OPA, the OPA policy is evaluated against the CheckRequest so the sharing of metadata in the State will not be sufficient. Is your ask that the passthrough service support modifying the request that will be evaluated against the OPA policy?

**Comment by sam-heilbron** [comment]
My mistake, the OPA policy is evaluated against the CheckRequest AND State. See the docs here https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/opa/#opa-input-structure for more details. The docs outline using `input.state.jwt` where the jwt property is setting during OIDC auth. The passthrough service could set a property using the DynamicMetadata that I pointed out in the above comment, and that property will be store in the state. Let's call that property, `passthrough_property`. Then, the OPA policy could evaluate `input.state.passthrough_property`.

Since this feature is supported at the moment, I will close this issue
