### ISSUE TITLE
Gloo 1.6 -> 1.7 upgrade flow improvements

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#4320]
**Describe the bug**
Ratelimit and extauth currently use v2 discovery requests to get xds config.

Gloo 1.6 supports both envoy API v2 and v3 on the server side. For Gloo 1.7, we will only be using v3.

We should ensure that now potential blips in service can occur during upgrades, by ensuring the server is updated first to a version that supports v2 and v3, then upgrade clients to use v3. Then and only then can we safely go to a server version that doesn't have v2 api support.

**Expected behavior**

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version
- Kubernetes version

**Comment by kdorosh** [comment]
so the upgrade flow is (v2 client and server) 1.5.x -> (v2 client and v2/v3 server) 1.6.0 -> (v3 client and v2/v3 server) 1.6.<latest> -> 1.7 (v3 client and v3 server)

**Comment by sam-heilbron** [comment]
We opted to continue to serve rate-limit and ext-auth using v2 discovery. As long as the go-control-plane supports v2 (even though it is deprecated) we are OK. There is an open issue (https://github.com/solo-io/gloo/issues/4369) and explanatory comment (https://github.com/solo-io/gloo/pull/4372) are why we are using v2 and that we'd like to maintain it ourselves instead of relying on the go-control-plane.

**Comment by sam-heilbron** [comment]
We opted to continue to serve rate-limit and ext-auth using v2 discovery. As long as the go-control-plane supports v2 (even though it is deprecated) we are OK. There is an open issue (https://github.com/solo-io/gloo/issues/4369) and explanatory comment (https://github.com/solo-io/gloo/pull/4372) are why we are using v2 and that we'd like to maintain it ourselves instead of relying on the go-control-plane.
