### ISSUE TITLE
upstream session affinity IDs to be shared across gateway proxies

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4445]
Given scaled gateway-proxies,
When using upstream session affinity, backed by a cookie,
What about a distributed system for (upstream) session management, like Redis. 
Does it make sense to store affinity sessions in Redis?

**Comment by antonioberben** [comment]
Similar issue from another custoemer:

They have 3 replicas and they have configured loadbalancer "lbHash" as described in [here](https://docs.solo.io/gloo-edge/master/installation/advanced_configuration/session_affinity/) 

The problem comes when kubernetes (kube-proxy) round robin across the 3 replicas and each of them (envoy)  has its own loadbalancer pointing to a different cluster endpoint.

**Comment by antonioberben** [comment]
@kevin-shelaga, is it possible you share in here your solution? It might be helpful for people who are searching through the issues. Thank you

**Comment by antonioberben** [comment]
Session affinity as described in the [docs](https://docs.solo.io/gloo-edge/latest/installation/advanced_configuration/session_affinity/) works only if the upstream endpoints are the same. But, when the upstream endpoints change, the session is not sticky anymore.

Scenario:
Following the steps from the [docs](https://docs.solo.io/gloo-edge/latest/installation/advanced_configuration/session_affinity/) scale out the replicas to 4 so that you will have following pods in order of creation:
```
sessionAffinity-app[1]
sessionAffinity-app[2]
sessionAffinity-app[3]
sessionAffinity-app[4]
```
Run the curl to the app, through gloo, until you reach the `sessionAffinity-app[4]` (it is important to make sure you are reaching the latest created pod)
```
curl $GATEWAY_IP/count -H "x-test-affinity: true"
```
It is expected that you will always hit this very same pod given the sessionAffnity.

Now, delete de other pods making sure that the only remaining pod is the one you were hitting (`sessionAffinity-app[4]`).
So you will kill:
```
sessionAffinity-app[1]
sessionAffinity-app[2]
sessionAffinity-app[3]
```

New replicas will be created. And you will have something like:
```
sessionAffinity-app[4]
sessionAffinity-app[5]
sessionAffinity-app[6]
sessionAffinity-app[7]
```

Run again the curl command. But you will hit  a different pod rather then the expected one: `sessionAffinity-app[4]`

This will probe that session affinity only work as long as the order of the apps is respected.
