### ISSUE TITLE
Improve ci flake performance

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#4491]
**Is your feature request related to a problem? Please describe.**
Test grid and advanced metrics collecting for testing and identifying flakes

**Describe the solution you'd like**
One possible solution is something similar to https://testgrid.knative.dev/serving#istio-latest-no-mesh&exclude-non-failed-tests=20

**Describe alternatives you've considered**

**Additional context**

**Comment by kdorosh** [comment]
Other ideas to improve performance include:
- making ci easy to re-run in parts (rather than re-running all of ci)
  - GH actions doesn't seem to support this on matrix, may want to consider circle ci

**Comment by kdorosh** [comment]
Test flakes on releases came up again as action item in team retro. We can explore:
- [ ] breaking ci into smaller, separately re-runnable chunks
- [ ] re-running tests a certain amount of times in ci
- [ ] hourly/nightly builds of master to detect flakes

**Comment by sam-heilbron** [comment]
We have been actively addressing this as part of recent stability work (https://github.com/solo-io/solo-projects/milestone/18). In Gloo OSS build-bot rarely if ever flakes, and the same is true for Github Action regression tests. Due to improved caching and test writing, these tests now take 15-20 minutes and per recent team feedback, flakes are no longer a problem in this repo.
