### ISSUE TITLE
Properly document helm generation process

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#454]
Currently our projects generate helm using a make target, `manifest`, in order to include the version number from the go pacakage. This means that the values templates are only processed if the added values are present in the `values.go` file as well. This process is not currently well documented anywhere in the repo.

We should also document Helm dev process, for instance Goland plugin for Kubernetes and helm charts.

**Comment by kdorosh** [comment]
Are these docs sufficient? https://github.com/solo-io/gloo/tree/master/install/helm

If the point is to explain why you need to add properties to `values.go` for them to render in the generated values files, we could add that here.

Separately, it may be nice to explain the design decision behind generating our values files from templates, rather than just directly modifying a values file itself. Why is it setup this way?
