### ISSUE TITLE
Save envoy last valid config as config map and bootstrap envoy using it. 

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#4839]
Being able to persit the last valid envoy configuration as a configmap, then when starting envoy pod (pod restart/ autoscalling ..) it will take the last valid config as an initial bootstrap config. 

This can be useful in case envoy restarts and gloo is down for some reason.

**Comment by chrisgaun** [comment]
We need to get thinking about how we are going to tackle this.

**Comment by EItanya** [comment]
> We need to get thinking about how we are going to tackle this.

Let's schedule something, I was just thinking through the details of implementing something like this.

**Comment by kdorosh** [comment]
## Design Proposal for improving failure scenarios for Gloo Edge

These proposals are an attempt to harden Gloo Edge to failures in a way that protects the data-plane from request errors.

For example, let's use the scenario where the gloo deployment (the xds server) is in a crash loop due to invalid configuration (e.g. route replacement disabled, on a version before schema validation, or a bug in gloo). The fleet of envoys will continue to serve requests using the last valid configuration they received from gloo. A common error-scenario here is that envoy is often scaled with request volume (i.e., autoscaling) and any new envoys started during this time (for any reason, e.g. node update and rollout, pod evicted by scheduler) will start up without any xds configuration and be unable to serve requests. This is the kind of scenario we should protect against.

### Option 1: Write last valid XDS config to ephemeral volume

The proposal here is to write the last xds config somewhere where it can be reloaded by Gloo and served again.

##### Option 1a: `emptyDir`

write to `emptyDir`:

pros:
- simple
- k8s-storage agnostic

cons:
- as gloo crash loops longer and longer, it may take longer for it to be up briefly and give the last valid config
- `emptyDir` only persists across restarts on the same node

Both of these cons are disqualifying.

##### Option 1b: `Secret`

write to a k8s `Secret` (configmap not a choice here since sensitive config is in the xds snapshot):

pros:
- simple
- k8s-storage agnostic

cons:
- as gloo crash loops longer and longer, it may take longer for it to be up briefly and give the last valid config
- etcd (the backing store behind k8s api resources) has a 1mb limit, which we will likely exceed

Both of these cons are disqualifying.

### Option 2: Write to persistent volume

write to a k8s persistent volume such as [aws elastic block store](https://kubernetes.io/docs/concepts/storage/volumes/#awselasticblockstore)

pros:
- shares config across gloo pods
- persists across restarts

cons:
- as gloo crash loops longer and longer, it may take longer for it to be up briefly and give the last valid config
- requires infrastructure-specific setup to persist this backup out of cluster
- unknown scaling limits with writing to remote disk often and quickly

The first and last cons are disqualifying.

### Option 3: XDS-relay (opting for this one)

Build on [this xds relay](https://github.com/envoyproxy/xds-relay) project or roll our own.

Introduce a new component to separate the lifecycle of the gloo deployment from the xds servers that the envoys get their requests from.

The new request flow would be:

- envoy -- xds request --> xds-relay -- xds request --> gloo

This means that if Gloo were to enter a crash loop, the xds relay component would still be live (perhaps as a daemonset or scaled to numerous replicas) for any new envoys to fetch the last valid configuration from.

pros:
- persists across gloo restarts by decoupling lifecycle

cons:
- without some kind of zookeeper-style leader election and config sharing, or persistent storage akin to above, if every single xds-relay server is restarted (e.g. node rollout to update kernel version) they will all have no configuration to serve
  - we might be able to work around this using an `emptyDir` on a daemonset

**Comment by kdorosh** [comment]
follow up work:
- [ ] ensure all caches get populated in regression test
- [ ] persist across restarts with emptydir
