### ISSUE TITLE
undefined: labels.AreLabelsInWhiteList

### ISSUE THREAD

**Issue by araj-cloud** [solo-io/gloo#4928]
When trying to use solo with k8s 1.20 and above getting the following error 
github.com/solo-io/gloo@v1.7.11/projects/gloo/pkg/plugins/kubernetes/eds.go:293:11: undefined: labels.AreLabelsInWhiteList

Looks like this function is replaced with IsSubset
https://github.com/kubernetes/kubernetes/pull/95179

Can someone take a look at this?

**Comment by kdorosh** [comment]
Hi @araj-cloud , I got some context offline here (sounds like you're trying to build `glooctl check` into your ci pipeline?). If so, I think we should turn this into a feature request for a REST API in gloo that exposes this information (similar to our validation API) or using metrics.

We actively discourage pulling in the Gloo repo as a dependency (preferring https://github.com/solo-io/solo-apis for its slim dependencies) because you will also pull in our k8s versions, which may not be compatible or compile with your k8s version (the problem you are hitting here).

If we were to upgrade our k8s version here, we might break older users. Hence solo-apis and discouraging pulling in Gloo as a dependency.
