### ISSUE TITLE
Staged rate limiting before/after auth for a route

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#5014]
**Is your feature request related to a problem? Please describe.**
Customer would like the ability to anonymous rate limit requests to the extAuth server, with 1 set of limits. But after auth, rate limit with a different set of limits

**Describe the solution you'd like**
Add the ability to have staged rate limiting, before and after auth stages.

**Describe alternatives you've considered**

**Additional context**

**Comment by sam-heilbron** [comment]
This would be very similar to our staged JWT API which was introduced by Sai : https://github.com/solo-io/gloo/pull/4034

**Comment by kdorosh** [comment]
@kevin-shelaga what use case is the customer trying to solve here that gloo edge does not support today?

the two use cases i can think of for why you'd want to run ratelimit both before _and_ after extauth are to:
- prevent DDOS to extauth, e.g. IDP provider
- improved latency on failure in the case of anonymous rate limits breached

otherwise, users could just run ratelimit after extauth (as is the default today) and have separate rate limits for both auth and unauthed users. We support this today, whereas adding support for stages (a prereq for the original request) is a fair chunk of envoy work

**Comment by kevin-shelaga** [comment]
@kdorosh The use case is essentially this. Rate limit before extAuth by remote_address thus limiting the amount of time a user with accidentally invalid credentials is hammering the extAuth service. Preventing extra load/hops for requests that are otherwise invalid anyways. 

Once the user is authenticated, then a separate set of rate limits can be used. 

You can think of this as a non-malicious ddos from a user with expired credentials.

**Comment by sam-heilbron** [comment]
@kevin-shelaga I may have dropped the ball on this. I think the 2-staged rate limiting support will solve this use case. Could you confirm that for me, and if so close this issue?

**Comment by kevin-shelaga** [comment]
@sam-heilbron Yes, 2 stage rate limiting should solve this use case.
