### ISSUE TITLE
license_secret_name helm value not found in documentation

### ISSUE THREAD

**Issue by antonioberben** [solo-io/gloo#5071]
For the helm chart, `license_secret_name` is not described in the documentation (https://docs.solo.io/gloo-edge/latest/reference/helm_chart_values/).

Thank you.

**Comment by MitchAman** [comment]
It is listed on master (https://docs.solo.io/gloo-edge/master/reference/helm_chart_values/enterprise_helm_chart_values/), but it could use a description.

**Comment by Rachael-Graham** [comment]
We are getting the same helm chart value in Mesh as well ([PR](https://github.com/solo-io/gloo-mesh-enterprise/pull/4633/files#diff-19d5f62e3d150c20e84faf2a60fa70cafcbfc183d79c73c8e17276ea53088fcfR20)), so I'd like to use this issue for both Edge and Mesh to 
1) In the reference docs, add a better description, and 
2) In the setup docs, add using the secret as an option instead of providing the license directly
