### ISSUE TITLE
CI Test Flake: can modify upstreams repeatedly, and endpoints don't lag via EDS 

### ISSUE THREAD

**Issue by sam-heilbron** [solo-io/gloo#5149]
**Describe the bug**
```
[Fail] endpoint discovery (EDS) works gRPC [It] can modify upstreams repeatedly, and endpoints don't lag via EDS 
/home/runner/work/gloo/gloo/test/kube2e/eds/eds_test.go:171
```

**Expected behavior**
The test is deterministic 

**Additional context**
Logs: https://github.com/solo-io/gloo/pull/5148/checks?check_run_id=3303722156

**Comment by MitchAman** [comment]
https://github.com/solo-io/gloo/runs/3323896590

**Comment by artberger** [comment]
I hit this in [this PR,](https://github.com/solo-io/gloo/pull/5205/) too.

**Comment by MitchAman** [comment]
https://github.com/solo-io/gloo/pull/5190/checks?check_run_id=3402506137

**Comment by bewebi** [comment]
Taking a brief look with some spare time
I highly doubt this is it, mainly because the rest and gRPC tests both seem to flake, but the two aren’t formatted the same
rest’s `It` is a [one liner](https://github.com/solo-io/gloo/blob/master/test/kube2e/eds/eds_test.go#L161) while gRPC [intercepts failures and then expects the list of those to be empty](https://github.com/solo-io/gloo/blob/master/test/kube2e/eds/eds_test.go#L170-L172)
I think it's an artifact leftover from the fact that gRPC test originally expected failure and it seems like they should behave the same
I’m also not really clear why the actual failure seems to be missing from logs
