### ISSUE TITLE
Invalid route replacement doesn't work when route table has incorrect prefix

### ISSUE THREAD

**Issue by malmanzor** [solo-io/gloo#5154]
**Describe the bug**
I have configured invalid route replacement in gloo edge and in most cases creating an invalid route table will not affect other routes from being processed by gloo and made reachable. However, if I create a route table that doesn't match a virtual service's prefix then this seems to break invalid route replacement and any new routes that I create will not be reachable.

**To Reproduce**
1. Create a virtual service with a prefix `/`
2. Create a route table associated with the virtual service with the prefix `bad`
3. Create a valid route table associated with the virtual service with the prefix `/valid`
4. The route `/valid` is not accessible until the bad route table is deleted

**Expected behavior**
Attempting to access the route specified by the invalid route table should return a 404 and route tables added after the invalid one should be accepted by gloo and made reachable.

**Additional context**
Gloo edge version 1.8.4

**Comment by chrisgaun** [comment]
Might be higher priority because not everyone would have their own validation.

**Comment by sam-heilbron** [comment]
Invalid route replacement docs: https://docs.solo.io/gloo-edge/latest/guides/traffic_management/configuration_validation/invalid_route_replacement/

**Comment by sam-heilbron** [comment]
@chrisgaun What version of gloo will this be backported to?

**Comment by chrisgaun** [comment]
@sam-heilbron as a bug, fix should be applied to all supported versions

**Comment by jenshu** [comment]
fixed via https://github.com/solo-io/gloo/issues/5502

Note, invalid route replacement doesn't come into play for this (not sure it would make sense anyway, since there'a a prefix mismatch between parent and child and unclear what route would be replaced). Instead the fix is to drop the invalid route during gateway translation (with a warning on both the RouteTable and parent VS), and allow only the valid route to make it onto the Proxy
