### ISSUE TITLE
glooctl uninstall -n my-namespace deletes the namespace

### ISSUE THREAD

**Issue by jtlz2** [solo-io/gloo#527]
I installed gloo into a custom namespace (which housed my other microservices), and to tear it down I ran (as per instructions):

    glooctl uninstall -n my-namespace

This had the unintended consequence of destroying my namespace :(

Is there a way to avoid this damage in future??

**Comment by rickducott** [comment]
Hey @jtlz2 sorry about your experience. The expectation was that gloo would be installed into a separate namespace, but we can find something safer. One idea... rather than run:
` kubectl delete ns my-namespace`

We could run: 
`kubectl delete all -n my-namespace -l gloo` 

That would clean up the gloo resources, which are labeled with "gloo=...", minus the namespace itself. The namespace could then be cleaned up if there were no other resources in the namespace, or if a flag was provided to the CLI.

**Comment by jtlz2** [comment]
@rickducott No problem at all and the prompt feedback is much appreciated.

**Comment by rickducott** [comment]
We are treating this as a bug and will be working on it soon (a few things ahead in the queue)

**Comment by rickducott** [comment]
Another thing that came up related to this... 

Wanting to switch from gloo enterprise to gloo open source, you need to uninstall one then install the other. In this case, it is not desirable to `kubectl delete all ...` in the namespace, just delete the objects referenced in the install manifest. 

At other times, you may want to delete everything, including the namespace and the CRDs: #433

**Comment by rickducott** [comment]
@jtlz2 we have merged in a fix that provides more safety and control during `glooctl uninstall`, see #580. Thanks for the feedback
