### ISSUE TITLE
expose ignore_health_on_host_removal on upstreams

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#5276]

**Comment by sam-heilbron** [comment]
`ignore_health_on_host_removal` is a field on the envoy cluster: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#config-cluster-v3-cluster

We need to expose this on our Upstream config: https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/upstream.proto 

so that it is configured on the cluster during our translation loop: https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/translator/clusters.go#L57
