### ISSUE TITLE
forwarding headers back to gloo

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#549]
I would like to use gloo as a external and internal gateway with host based routing.  The problem is that my internal services do not forward host headers. 

I see that gloo has Istio integration.  I plan to use that with mTLS.  

My question is, is it possible to have Istio forward host headers so that I do not have to modify every service?  Then, when a request come from one of my internal services back to the gateway proxy, it will have the proper host header so that it can be dispatched to the proper virtual service?  If so, I think this would make for a nice addition to your documentation on Istio integration.

**Comment by yuval-k** [comment]
Istio can append headers, but I think envoy disallows changing the ":" headers.

I think you can have istio add it as a regular header, and have gloo route with that header?

**Comment by christian-posta** [comment]
Im not sure I fully understand what you're asking. Can you give a quick example @derrickburns ?  can you clarify "virtual service" in your context to either Istio or Gloo virtual service and also when you say "internal/external" are you referring to a particular cluster? or your entire org?

**Comment by derrickburns** [comment]
Hi @christian-posta, 
I will try to be more clear.

I have a Gloo virtual service that I would like to effectively clone, with each running in a separate Kubernetes namespace.  The reason for this is for developers to be able to test different versions of different images in one virtual service without affecting the other.

I would prefer to use a single AWS load balancer to access the two virtual services.  Gloo appears to support having each virtual service supports a different host (host based routing).  This would work for me IF the upstreams that are used in the virtual service DID NOT need to route to each other indirectly through the Gloo gateway. At present, some of the upstreams access others using the same path based routing that is implemented in the Gloo gateway.  However I do not believe that the upstreams forward the host header back to the Gloo gateway.  If they did, then there would be no problem. I would prefer not having the modify each upstream service to do so (at this time).  Rather, I would prefer simply that the host header associated with all traffic to the upstreams in one of the virtual services be forwarded back to the Gloo gateway.

**Comment by derrickburns** [comment]
Alternatively, can I use two instances Gloo Gateway and two load balancers in the same Kubernetes cluster?

**Comment by christian-posta** [comment]
Could you use a simple example?

Sounds like you have something like `foo.svc` and `bar.svc` and you want to route to them using a VirtualService in Gloo at a FQDN of `new.svc`. But you may want to try out new versions/images of `foo.svc` and `bar.svc` so you may want to create a different VirtualService in Gloo called `new1.svc` that routes to those?

But then you have some internal traffic (ie, `foo.svc` wants to call `bar.svc`) that also goes through Gloo?

And when `foo.svc` calls `bar.svc` through the Gloo Gateway, you need the host header to be `Host: bar.svc`? so basically you need to support both `new.svc` at the edge AND `bar.svc` for internal traffic? And do so without modifying the `foo.svc` so that it explicitly sets the host header to bar.svc?

Sorry to draw this out more, but just want to make sure I'm understanding exactly what you're asking. Otherwise I'd just be suggesting solutions to problems you don't have :)

**Comment by derrickburns** [comment]
And, yes, @christian-posta, you described my scenario well.

**Comment by rickducott** [comment]
I'm going to mark this as stale. I think there are some things we could explore with the current product, including having multi-tenant install, as well as utilizing some gloo routing and delegation features. I'm going to assume we are unblocked and this is less of a priority, but please reopen if I am mistaken.
