### ISSUE TITLE
Allow configuring envoy stats_config through helm

### ISSUE THREAD

**Issue by malmanzor** [solo-io/gloo#5537]
**Is your feature request related to a problem? Please describe.**
The gateway-proxy pods produce a large number of Prometheus metrics. In a sizable cluster these metrics can overwhelm the Prometheus servers that scrape the metrics endpoint. 

Envoy bootstrap configuration contains a `stats_config` block that can used to filter the metrics that are exposed to prometheus https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/metrics/v3/stats.proto#envoy-v3-api-msg-config-metrics-v3-statsconfig . However, the `stats_config` is not exposed through helm and needs to be manually added to the `gateway-proxy-envoy-config` config map.

**Describe the solution you'd like**
Allow gloo users to customize their `stats_config` using helm instead of needing to modify the configmap manually.

**Describe alternatives you've considered**
Manually editing the configmap

**Comment by sam-heilbron** [comment]
Currently supported statsConfiguration in helm: https://github.com/solo-io/gloo/blob/4c22a38a6c10feb0ce7f87b91596f47c62593834/install/helm/gloo/generate/values.go#L527

gw-proxy-config-map helm template: https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/9-gateway-proxy-configmap.yaml

**Comment by mburtless** [comment]
Investigated this a little more and the statsConfiguration referenced above is not actually used to set the `stats_config` setting in gw-proxy-config-map.  It looks like it's used to configure a listener for exposing a stats endpoint on the `admin_port_cluster` to prometheus.

I can pick up this issue, I just need feedback on where the config for `stats_config` values should live in the helm chart, since it's function is different then what the `stats` block is currently used for.

**Comment by jenshu** [comment]
new helm value `envoyStatsConfig` will be available in:
Gloo OSS v1.15.0-beta18, v1.14.11, v1.13.21
Gloo EE v1.15.0-beta4, v1.14.7, v1.13.21
