### ISSUE TITLE
WAF rules cause gateway proxy crash 

### ISSUE THREAD

**Issue by saiskee** [solo-io/gloo#5558]
the @validateXmlSchema rule causes gateway proxy to crash in gloo enterprise v1.6.27

**Comment by sam-heilbron** [comment]
The bug has been identified and fixed in ModSecurity: https://github.com/yuval-k/ModSecurity/tree/v3.0.4-no-schema-crash

The fix was pulled directly into a hotfix for 1.17.x: https://github.com/solo-io/envoy-gloo-ee/pull/213/

Remaining work:
- [ ] Apply hotfix to 1.19.x branch, release
- [ ] Apply hotfix to 1.18.x branch, release
- [ ] Update version in solo-projects:master, release
- [ ] Update version in solo-projects:1.9.x, release
- [ ] Update version in solo-projects:1.8.x, release
- [ ] Update version in solo-projects:1.7.x, release
- [ ] Update version in solo-projects:1.6.x, release

*Note: The work does not need to be completed in the order it is listed. We need to get the hotfix to our main branches first, and then all backports can be done in parallel*
