### ISSUE TITLE
Gloo Overview dashboards are not created when connecting to a external grafana installation.

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo#5813]
### Version

1.10.x (latest stable)

### Is your feature request related to a problem? Please describe.

Gloo Overview dashboards referenced in the docs ( https://docs.solo.io/gloo-edge/master/guides/observability/grafana/dashboards/#whole-cluster-dashboard) are not created when connecting to a external grafana installation.

### Describe the solution you'd like

The automatic creation of the gloo overview dashboards

**Comment by bewebi** [comment]
After catching up with @pszeto my understanding of this issue is that there are two components:

- Making the default dashboard templates available for the user to add to their Grafana installation (or, if possible, get them added on gloo install)
  - This could entail publishing templates somewhere for our customers to download and import
- Even once the templates are loaded into an external Grafana installation, with the correct datasource specified, the data does not populate
  - We will have to identify why this is in order to determine and execute the solution

**Comment by bewebi** [comment]
Default dashboards are automatically created in custom grafana installations as of Enterprise 1.11.0-beta8
There are further issues encompassed in solo-io/dev-portal#2164
