### ISSUE TITLE
Metrics for upstream doesn't accurately show when using an external grafana / prometheus installation

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo#5814]
### Gloo Edge Version

1.11.x (beta)

### Describe the bug

The queries used by custom upstream dashboards created by the observability pod are not set properly to pull from the default Prometheus data source. It references a gloo datasource.

### Steps to reproduce the bug

1. install gloo edge pointing to an external grafana stack
2. create a deployment and service
3. Navigate to the Dashboards  and select the upstream dashboard for the service.

### Expected Behavior

The panels should have the correct metrics.

**Comment by bewebi** [comment]
After catching up with @pszeto, my understanding of this problem is that once the user creates the `gloo` datasource in their Grafana install, upstream graphs are able to populate
To resolve this more generically we need to expose the option for users to specify an alternate datasource to override the `gloo` default
