### ISSUE TITLE
REDIS server with TLS enabled integration

### ISSUE THREAD

**Issue by jmunozro** [solo-io/gloo#5857]
### Version

1.10.x (latest stable)

### Is your feature request related to a problem? Please describe.

You can provide your own redis server for rate-limit, but it does not work if the server is exposing TLS.
This is common in cloud services (for example AWS with option `Encryption in-transit` activated)
![image](https://user-images.githubusercontent.com/35881711/151964207-19d8de28-69db-469f-8206-d9fc46b07ee4.png)

### Describe the solution you'd like

Please find attached files to reproduce locally: [poc.zip](https://github.com/solo-io/gloo/files/7978156/poc.zip)
 

### Additional Context

This is related to: https://github.com/solo-io/gloo-mesh-enterprise/issues/2291

**Comment by birkland** [comment]
Just as an update, [rate-limiter](https://github.com/solo-io/rate-limiter) 0.6.0 was released as part of addressing the [analogous issue to this one](https://github.com/solo-io/gloo-mesh-enterprise/issues/2291) on for Gloo Mesh.  Gloo Mesh depends on that image directly, but my understanding is that Gloo Edge uses a rate-limiter image has additional customizations, but is based off the same image.  

If that's the case, then a significant prerequisite for addressing this issue is done, and the remaining would involve building Gloo Edge's rate limiter image on top of this work (plus perhaps incorporating the new [helm chart values](install/helm/rate-limiter/values-template.yaml) supported by the v0.6.0 release)

**Comment by jackstine** [comment]
I will update this ticket again with instructions on how to build redis tls once a release of v1.12 has been released. If a release of v1.12 is needed sooner let me know.
