### ISSUE TITLE
Allow constraining certgen's Secret access permissions to Gloo installation namespace

### ISSUE THREAD

**Issue by Spoonbender** [solo-io/gloo#5960]
### Version

1.10.x (latest stable)

### Is your feature request related to a problem? Please describe.

The feature request is related to security hardening and following the "least required privileges" principle. 
The `certgen` job is created with a `ClusterRole` and `ClusterRoleBinding` which grant it permissions to access all secrets in the cluster.
It seems that for our use case, `certgen` can work properly with a Role and RoleBinding in Gloo's installation namespace instead.

### Describe the solution you'd like

I'd like to be able to tell the Helm chart to create the RBAC of `certgen` using a `Role` and `RoleBinding`, via Helm values.

This could be a new value, or utilize the `.Values.global.glooRbac.namespaced` value and follow the same pattern of setting the `namespace` and picking the Role and RoleBinding `kind` accordingly (`kind: {{ include "gloo.roleKind" . }}Binding`, as we can see for other RBAC-related resources).

### Describe alternatives you've considered

Alternatively, if `certgen` only needs permissions to Gloo's installation namespace (i.e. there is no use case for cluster-wide permissions) then a viable solution is just to change to Role and RoleBinding without an opt-in mechanism.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1206779676254253) by [Unito](https://www.unito.io)

**Comment by Bslabe123** [comment]
So adding an option to make the certgen job namespace scoped isn't going to work since we look for the validating webhook config which is a cluster scoped resource. There's no way to access it without the ClusterRole so the proposal in the comment isnt valid. We could rework how we get the cert into the validating webhook if SAP is really stuck though.

**Comment by shahar-h** [comment]
Unfortunately the solution doesn't work for our use case because setting `global.glooRbac.namespaced=true` applies to all RBAC resources in Gloo chart, so i.e. [gloo-upstream-mutator](https://github.com/solo-io/gloo/blob/main/install/helm/gloo/templates/20-namespace-clusterrole-gateway.yaml#L53) will now become a Role instead of ClusterRole which is not what we want because our upstreams are held in various namespaces.
Does [gateway-certgen-job](https://github.com/solo-io/gloo/blob/main/install/helm/gloo/templates/6.5-gateway-certgen-job.yaml) really need access to cluster wide secrets? If not why not to use a Role hardcoded?
If there is such use case can you add a configuration that allows to choose Role/clusterRole only for [gloo-gateway-secret-create](https://github.com/solo-io/gloo/blob/main/install/helm/gloo/templates/6.5-gateway-certgen-job.yaml#L148)?

**Comment by jenshu** [comment]
reopening until latest comment is resolved

**Comment by davidjumani** [comment]
This is in OSS v1.17.0-beta18 and Enterprise v1.17.0 when released
