### ISSUE TITLE
glooctl uninstall --all fails if ns doesn't exist

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#602]
Should clean up without failing

**Comment by EItanya** [comment]
@rickducott Quick question on this one, It still has to fail, because it does not know where gloo is located that it should delete it. There are a couple options:
1) Fail with a more helpful error message
2) Make a best guess as to where Gloo is and delete it

It seems dangerous to just go ahead with a delete not knowing which namespace it exists in

**Comment by ashleywang1** [comment]
or 3. Don't error out, but effectively do nothing as there is nothing to clean up.
