### ISSUE TITLE
Allow use of stale reads when querying Consul

### ISSUE THREAD

**Issue by solodamon** [solo-io/gloo#6185]
### Version

1.10.x (latest stable)

### Is your feature request related to a problem? Please describe.

Consul supports the use of "stale reads" which effectively allows non-leader nodes to respond to queries.  In particularly large organizations, this can have dramatic performance improvements with relatively little risk of inconsitent data.  Requiring consistent reads introduces substantial risks of overwhelming large Consul environments which actually leads to substantially more challenging failure modes than occasionally receiving outdated results.

### Describe the solution you'd like

Ideally the "stale" flag would be used to allow any server to respond, regardless of whether it is the leader.

### Describe alternatives you've considered

The only alternative is to harden Consul against performance degredation due to requiring consistent reads.  This is much more difficult than allowing stale reads.

### Additional Context

HashiCorp provides the following documentation on Consul's read consistent options:

https://www.consul.io/api-docs/features/consistency

**Comment by chrisgaun** [comment]
@yuval-k has more context if needed

**Comment by jackstine** [comment]
Added consistency to both [Settings](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk/) and the Consul API.

Still needs to add to solo-kits repo as well, for example this is one call to the [consul API.](https://github.com/solo-io/solo-kit/blob/master/pkg/api/v1/clients/consul/resource_client.go#L191).  Please examine the Consul API reference as needed to add to the QueryOptions.  Any Consul API call that can have the QueryOptions (sometimes it is called with null) can have it's consistency mode changed.

For example [here](https://github.com/solo-io/solo-kit/blob/master/pkg/api/v1/clients/consul/resource_client.go#L145) is where we call the API with a `nil` value. This can be changed to add the Consistency Mode.

**Comment by tmartinsolo** [comment]
Some additional comments on the PR:

https://github.com/solo-io/gloo/blob/4f133dd2be0875463754fecc84c1eced7d4202fd/projects/gloo/pkg/plugins/consul/plugin.go#L77

This should look like (psuedo-code kinda, i know options doesn't exist)
	instances, _, err := p.client.Service(spec.GetServiceName(), "", &api.QueryOptions{Datacenter: dc, RequireConsistent: options.RequireConsistent, UseCache: options.UseCache, AllowStale, options.AllowStale})

(https://solo-io-corp.slack.com/archives/C031NRKP1UL/p1650045977749209)
https://github.com/hashicorp/consul/blob/main/api/api.go#L101 if you wanna get fancy for enterprise folks, supporting Namespace would be a big win too.
[api.go](https://github.com/hashicorp/consul/blob/main/api/api.go)
type QueryOptions struct {

[plugin.go](https://github.com/solo-io/gloo/blob/4f133dd2be0875463754fecc84c1eced7d4202fd/projects/gloo/pkg/plugins/consul/plugin.go)
    instances, _, err := p.client.Service(spec.GetServiceName(), "", &api.QueryOptions{Datacenter: dc, RequireConsistent: true})

would this belong under consulUpstreamDiscoverySettings maybe - like u.consulUpstreamDiscoverySettings.RequireConsistent?

Anywhere that calls like p.client.Health or p.client.Services will want to pass the same api.QueryOptions block.  Typically when doing this you instantiate the api.QueryOptions struct and just pass it around.

Some of the options in that struct linked above are not very useful because the client has sensible overrides (e.g.: Token, Datacenter) and some are almost never used and should only be overwritten on specific endpoints for very good reasons (like WaitHash/Near) 


if we could include hitting the .Services() api and then allowing filtering by tag (v1/catalog/services)  
  "foo": [
    "app_metrics",
    "bedev2",
    "bedev2Template=a839e3,1.78.0",
    "product=foo",
    "traefik.frontend.entryPoints=http",
    "traefik.frontend.passHostHeader=true",
    "traefik.frontend.rule=Host:asdf",
    "traefik.enable=true",
    "traefik.tags=http",
    "traefik.backend.loadbalancer.method=wrr",
    "traefik.backend.buffering.retryExpression=IsNetworkError() && Attempts() <= 2"
  ],
  "bar": [
    "bedev2",
    "bedev2Template=a839e3,1.78.0",
    "traefik.frontend.entryPoints=http",
    "traefik.frontend.passHostHeader=true",
    "traefik.frontend.rule=Host:asdf",
    "traefik.backend.loadbalancer.method=wrr",
    "traefik.backend.buffering.retryExpression=IsNetworkError() && Attempts() <= 2",
    "app_metrics",
    "traefik.enable=true",
    "traefik.tags=http",
    "product=bar"
  ],
  "baz": [
    "asdf",
    "st"
  ],
this is how some customers set traefik rules today, and having something similar to being able to filter using something similar to traefik.enable=true would be useful.

this is from curl https://consul/v1/catalog/services

https://github.com/Roblox/traefik/blob/v1.7_roblox/provider/consulcatalog/consul_catalog.go#L504-L517
this is the function they use at the moment

https://github.com/Roblox/traefik/blob/v1.7_roblox/provider/consulcatalog/consul_catalog.go#L217-L226
and here's how/where it's called
https://github.com/Roblox/traefik/blob/v1.7_roblox/provider/consulcatalog/consul_catalog.go

if you have a filtering system in-place for other areas (like filtering k8s services) that has a more generic system please of course use that.

The other option which would potentially flip how you use consul upside down would be to allow opt-in services -- so like having a catalog of 'opted-in' services in solo's data store which is fetched/used every poll period, so something like glooctl enable service pet-store maybe?

Please let us know if you have any additional questions on these requests/comments on the PR.

**Comment by chrisgaun** [comment]
Let's split out the new scope into another issue. This one is close to done.

**Comment by inFocus7** [comment]
For transparency(?)/update, @tmartinsolo created issue #6343 to split out their additional comments 👍
