### ISSUE TITLE
OIDC - call the revocation_endpoint on logout

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#6328]
### Is your feature request related to a problem? Please describe.

When the `logoutPath` is called, the user session is deleted (Redis and/or cookies)
We should also revoke the access token by calling the revocation endpoint on the IdP (if found during the OIDC discovery phase).

### Describe the solution you'd like

Not sure if the following RFC makes authority: https://datatracker.ietf.org/doc/html/rfc7009

**Comment by chrisgaun** [comment]
This may be dupe or similar issue.

**Comment by marcogschmidt** [comment]
@bcollard @inFocus7 It seems like the fix for this will address these two other issues as well:
- https://github.com/solo-io/gloo/issues/6179
- https://github.com/solo-io/gloo/issues/4410
Can you confirm?

**Comment by bcollard** [comment]
The fix looks good for this issue #6328
It should also help with #6179 

Regarding #4410, I would let it open because the request is a little bit different 👉 it's about terminating the session on the IdP / "OIDC Provider" side, which now looks to me like an edge case.

**Comment by inFocus7** [comment]
@marcogschmidt As bcollard said, it should help with #6179. A reason I could see it failing is if keycloak doesn't support `access_token` revocation(*).

(*) RFC 7009 states that revocation endpoints:
> MUST support the revocation of refresh tokens and SHOULD support the revocation of access tokens
so it's possible Keycloak only supports `refresh_token` revocation, while we're trying to revoke access tokens.

Luckily we already have revocation work done, so it _shouldn't_ be a big hurdle to revoke refresh_token since it'll just be swapping the [token passed to the endpoint](https://github.com/solo-io/ext-auth-service/blob/master/pkg/config/oidc/oidc_request.go#L198-L199). It would require a bit of planning on when/how we want to handle revoking `access_token` vs `refresh_token`, and I'm also not 100% sure how to get the refresh_token in the code.

**Comment by nfuden** [comment]
it looks like keycloak integration is not allowing for logout

**Comment by totallyGreg** [comment]
Debugging session revealed keycloak is correctly processing the revocation.  Salesforce however is keeping the connection active for 15 minutes.  This is seen by Keycloak which trusts Salesforce and thus regenerates a new access token.  Keycloak team and Salesforce auth team need to ensure that single signout is implemented in a way that revokes tokens in both places.  

This issue was successfully solved by https://github.com/solo-io/gloo/issues/6328 which can be closed.

**Comment by inFocus7** [comment]
Reopening while working on missing backports in review (v1.10.x) due to project dependencies. 

Issue is resolved, for v.11.x+ 👍🏼
