### ISSUE TITLE
Docs for 1.12: Caching

### ISSUE THREAD

**Issue by Rachael-Graham** [solo-io/gloo#6763]
### Version

master

### Describe the requested changes

(placeholder, will fill out soon)

**Comment by Nadine2016** [comment]
- Contact person: Nathan
- Enterprise-only feature
- Similar to how we do external auth and rate limiting today, there will be a new Helm value that, when you enable that, will create a caching server for you
- The caching server is managed by us and automatically deployed
- How it works:
  - You define the listener that this applies to
  - When a request comes in, it is routed to the upstream
  - The response from the upstream is automatically cached
  - The default caching time is 1 hour (but we should confirm that as it was not 100% clear)
  - Subsequent requests will receive the cached response
- The default caching server settings are determined by us and you cannot customize them for the initial release, hence you cannot change the caching time for example (https://github.com/solo-io/caching-service/blob/1878b088f6647be29a9bd805035bc9251477d967/pkg/settings/settings.go#L9)
- What they will let you do though is, in the Settings CRD, you can define the listener you apply it to and the matchers you want to include. For example, you can say to cache responses for `/ratings` and `/ratings?query=value` > so basically all the paths you want to treat the same way from a caching perspective (https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/enterprise/options/caching/caching.proto#L15)
- PR (includes the Helm values) https://github.com/solo-io/solo-projects/pull/3603/files
- they said at the end of the day, we can expect it to look like this https://docs.solo.io/gloo-edge/latest/guides/security/waf/#http-gateway but instead of `waf` it will be called `caching` and in there you define the caching server and the matchers
- Ways to verify this setup:
  - Responses are quicker
  - Upstream do not get subsequent requests (though Sam wanted to think about how we can actually test that, maybe just looking at logs??)

**Comment by nfuden** [comment]
Caching is enabled in enterprise via global.extensions.caching.enabled which defaults to false.
If it is set then a deployment of the caching service will spin up using the specified redis overrides. It does not currently support mtls but supports our other redis configuration options such as setting a password.
Our caching filter is an extension (implementing filter) for https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/cache and takes advantage of all the cache-ability checks applied by the upstream filter but provides the ability to store the cached objects in a given redis instance. Future extensions may be put in place to mutate or override specifics behaviors as desired.

**Comment by Rachael-Graham** [comment]
https://github.com/solo-io/gloo/pull/6846/
