### ISSUE TITLE
Allow the configuration of PDB API version

### ISSUE THREAD

**Issue by pseudonator** [solo-io/gloo#6989]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

Similar to [HPA](https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/8-gateway-proxy-horizontal-pod-autoscaler.yaml#L9) PDB API version should be configurable.

As of Kubernetes 1.21+ PDB has been [promoted to stable](https://kubernetes.io/docs/concepts/workloads/pods/disruptions/#pod-disruption-budgets).

During Gloo Helm install the following warning is noticed.
```
W0819 22:09:34.638390   60270 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
```

### Steps to reproduce the bug

Helm install

### Expected Behavior

Allowing the configuration of PDB API version

**Comment by kitarp29** [comment]
Could you explain the issue better @pseudonator ??

**Comment by Kostavro** [comment]
I will bump this and can explain @kitarp29 

PDB api policy/v1beta1 has been removed in kubernetes v1.25 : [https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125).

So, the PDB as it is now in this chart, can not be created and the helm deploy will fail because of it (if PDB is enabled).

**Comment by pseudonator** [comment]
Fixed as of https://github.com/solo-io/gloo/pull/8024
