### ISSUE TITLE
expose `validatingWebhookConfiguration` timeoutSeconds as configurable value

### ISSUE THREAD

**Issue by totallyGreg** [solo-io/gloo#7218]
### Version

1.11.x

### Is your feature request related to a problem? Please describe.

Customer has to manually adjust the timeout value from 10s to 30s after each upgrade via `kubectl patch`

Do so allows their developers to apply changes consistently without timeout errors in their environment

### Describe the solution you'd like

Would like to be able to define this timeout value via existing helm overrides.yaml

**Comment by sam-heilbron** [comment]
I like the idea! I think it would be valuable as part of this work to identify new features of the VWH API that are available that we could use, and expanding our usage of KubeResourceOverrides in the Helm API for the webhook (https://github.com/solo-io/gloo/blob/a9a0a5538e7308afa48131da3ef8e7c456fc3e63/install/helm/gloo/generate/values.go#L302) so that more fields are customizable.

@totallyGreg could you do some research into other enhancements to the VWH that customers would find useful so we can tackle them holistically?

**Comment by totallyGreg** [comment]
Addition feature.
> The webhook's caBundle should be updated to reflect the current self signed certificate used by TLS certs in secrets gloo-mtls-certs and gateway-validation-certs.
