### ISSUE TITLE
Make http port optional in K8s manifests

### ISSUE THREAD

**Issue by guydc** [solo-io/gloo#7377]
### Version

1.12.x (latest stable)

### Is your feature request related to a problem? Please describe.

Currently, the gloo edge chart enables and http port (default: 80) on both gateway-proxy service and pods:

- https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/8-gateway-proxy-service.yaml
- https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L227

While it's possible to disable the envoy http listener, the existence of the additional http port in k8s manifests leads to the creation of undesirable resources (e.g. hyperscaler firewall rules). 

### Describe the solution you'd like

It should be possible to disable the http port in the proxy service and pod manifests with appropriate helm chart values.

**Comment by kitarp29** [comment]
Can I take this up? @guydc @bobzoller 
Please assign it to me.

**Comment by SuperAayush** [comment]
Hey @guydc @chrisgaun!!
I would love to help with this issue, can you please assign it to me?
Also can you give me a lead on how can I get things easy for me?

**Comment by nfuden** [comment]
@SuperAayush we are happy to talk implementation details with you on this one it has a few moving parts that could be hard to hit without a measured survey. If you want we could talk through the process used once we complete this or if you are in our open source slack drop me a dm and we can talk about what you might want to do / if there is any other guidance we can give you. 
I admit to not checking the slack messages there often enough but it might be our best communication strategy.
Of course if you feel strongly about this issue in particular (the above text was in case it wasnt about the particular problem) we definitely can instead figure out how to best help this be tackled instead.

**Comment by irateswami** [comment]
👀

**Comment by SuperAayush** [comment]
> 

This is really nice of you @nfuden, I have dropped a message to you on Slack.
Thank You!!

**Comment by Bslabe123** [comment]
As per standup heres the proposal:

# Problem Summary:
When we create the k8s manifest for gloo via helm we expose all ports that could be used by default. In certain situations it may be prudent to not allow traffic on certain ports (i.e. HTTPS but no HTTP traffic). There also may be situations in which leaving a port open may lead to unneeded resources being created (as mentioned in the issue, hyperscaler firewall rules). We would like to introduce a toggle/convention to allow anyone building gloo helm charts to disable the exposing of certain ports.
# Design:
- A simple solution that would prevent the creation of additional settings would be to make 0 a reserved value for any httpPort field indicating that the port should be disabled, when rendering the helm chart we would wrap the port declaration in an if(port != 0)/else statement. We should also call this out loudly in the field description since its a less explicit toggle.
- Another approach would be to expose a new option for each httpPort field (along the lines of portEnabled) and follow the same approach as above but while using (portEnabled == true) as the condition. This approach is slightly more intuitive however would involve bloating our settings with another new value.

**Comment by Bslabe123** [comment]
We support the ability to generate Gateway objects (which are translated into Envoy listeners) in our Helm charts. If a Gateway is created, we also expose the corresponding Port on the gateway-proxy service. The ask seems to be that you would expect ports to only be exposed if there is a Gateway object which uses that port. Is that correct? By default we create an httpGateway and httpsGateway with a Gloo Edge installation. If you would like to disable the creation of either, you can use disableHttp(s)Gateway which, when set:
We don’t create the Gateway object: https://github.com/solo-io/gloo/blob/be77cfd8f64f3f056cce8265078a65c4136b07b1/install/helm/gloo/templates/_8-default-gateways.tpl#L155
We don’t expose the port on the gateway-proxy service: https://github.com/solo-io/gloo/blob/be77cfd8f64f3f056cce8265078a65c4136b07b1/install/helm/gloo/templates/8-gateway-proxy-service.yaml#L37
Can you explain why the current `disableHttpGateway` and `disableHttpGateway` toggles do not work for your use case?

**Comment by guydc** [comment]
Hi @Bslabe123. You're right, that should work, I was looking at the wrong service definition previously. 

We're actually using the `disableGeneratedGateways` value, which disables rendering of both gateways (and any future gateway), as we want complete control over listener management. We deploy our own ssl gateway, not via the helm chart. The `disableGeneratedGateways` is not considered by the service template, leading to both default ports remaining open.  

So, we can handle this in a couple of ways:
1. Keep the current behavior and configure both `disableGeneratedGateways` (listeners) and `disableHttpGateway` (port 80)
2. Treat `disableGeneratedGateways` like `disableHttp[s]Gateway` and disable all service ports, and introduce another mechanism to explicitly control which ports are open. 

For backwards compatibility, I think that (1) is preferable. Closing this issue.
