### ISSUE TITLE
Unable to expose functions with built-in ingress

### ISSUE THREAD

**Issue by xpepermint** [solo-io/gloo#741]
I installed a fresh K8S on DigitalOcean and then run `glooctl install knative` which says that includes an Ingress Controller. If I understand that correctly this means the I would be able to follow [this](https://gloo.solo.io/user_guides/basic_ingress/) and expose the petstore function to the public internet. I can't make this work. Should I install Nginx Controller and do this somehow (Nginx works for general services).

Please explain the right way of exposing knative function to the public internet on a public domain. Thank you!

**Comment by ilackarms** [comment]
hi @xpepermint,

gloo supports it's own kind of function routing. using aws lambda functions, rest and grpc functions, gloo routes can be created that directly target one of the supported function types. this can only be done (currently) via the gateway api.

gloo supports the knative ingress api allowing it to be run as the knative ingress without any configuration by the user. (simply write your knative crds as usual).

finally gloo supports the standard kubernetes ingress api for simple (direct to the service) routing.


each of these different modes are an installation option that can be selected with the cli or via the helm chart

**Comment by ilackarms** [comment]
these are eacj just a different means of configuring gloo. do you have a use case that requires invoking gloo functions with the v1beta1/ingress api?

**Comment by ilackarms** [comment]
gloo's gateway api (including function routing) can be accessed via the `virtualservice` and `gateway` crds

**Comment by xpepermint** [comment]
Huh, sounds great. What I need is just to enable function access from a public domain over http. I'm struggling with this for a long time. I can't find proper documentation for this. Would you be so kind and point me to an example or maybe give me a hint with a code snippet?

**Comment by ilackarms** [comment]
i'm trying to understand what you mean by `enable function access from a public domain`

if you want to access gloo from a public domain, you'll need to expose Gloo (specifically the `gateway-proxy` service inside of kubernetes) to the outside world. 

exposing this service to external traffic is no different from exposing any kubernetes service to external traffic. this can be done with a LoadBalancer if you're running kube on a cloud provider like AWS or GKE. otherwise you may want to look into NodePort, and configuring your domain to point to the ip/hostname of the node hosting the kube service.

**Comment by xpepermint** [comment]
I'm playing with this and a few minutes ago I managed to make it work :). It has nothing to do with gloo but with digitalocean's balancer issue. Thanks for help and closing ...
