### ISSUE TITLE
Add support for HMAC SHA1 in extAuth

### ISSUE THREAD

**Issue by afro-coder** [solo-io/gloo#7472]
### Version

1.13.x (beta)

### Is your feature request related to a problem? Please describe.

Currently only APR is supported in ExtAuth, we would like to add SHA1 to this to support use case like moving from Kong API that currently uses SHA1.

### Describe the solution you'd like

SHA1 support added in the extauth Basic auth section.

https://docs.solo.io/gloo-edge/master/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#basicauth

**Comment by sheidkamp** [comment]
@afro-coder - looking at the Kong docs (https://docs.konghq.com/hub/kong-inc/hmac-auth/) it looks like we need to specifically implement `hmac-sha1`. Can you confirm? thanks!

**Comment by afro-coder** [comment]
@sheidkamp yep that looks correct, their docs here just say SHA1 the Cx has just said SHA1 and the info you found seems to be the correct one

**Comment by sheidkamp** [comment]
Also want to make sure AirTel aware of the risks of SHA1...

In a nutshell:
* SHA1 by itself is insecure
* HMAC-SHA1 is secure BUT
* If the key is exposed it is less secure than other HMAC implementations (eg, -SHA256 or -SHA512)
(https://crypto.stackexchange.com/questions/26510/why-is-hmac-sha1-still-considered-secure)

Since this is a migration, it may not matter to them immediately, but it would also be good to know if they think they will want a stronger hashing algorithm in the future.

**Comment by sheidkamp** [comment]
@afro-coder - looks like in the short term, we have an HMAC plugin available for ext-auth: https://github.com/solo-io/hmac-auth. It would need to be updated to match Kong's rules for generating the message from which the signature is generated, looks like the spot is here: https://github.com/solo-io/hmac-auth/blob/88276731c1191df7a6679b54a4a3cf4d03351060/pkg/auth/auth.go#L78

I'll keep you in the loop about getting native support built into our ext-auth server.

**Comment by elcasteel** [comment]
I think this is a reasonable summary of the remaining work so that we can begin to divide and conquer the last pieces. 

**Gloo**
- [ ] Finalize API 
- [ ] Update documentation for AccountCredentialsSecret to include hmac use case (or create new secret and stuff around it)

** Extauth **
- [ ] Finish unit tests that are currently in progress
- [ ] Functionality fixes as potentially uncovered by tests

**Solo-Projects**
- [ ] Gloo translation (this is separate from translation in ext-auth-service repo)
- [ ] E2E test for config

**Comment by nfuden** [comment]
reopening due to sp portion
