### ISSUE TITLE
Extauth logging repeated messages every 10 seconds

### ISSUE THREAD

**Issue by huzlak** [solo-io/gloo#7546]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

1.24.x

### Describe the bug

Extauth reconciliation happens every 10s even when no changes are made to configs. It seems related to the fact that virtual host name gets '.' replaced during sanitizing.

### Steps to reproduce the bug

I haven't managed to reproduce locally, but there's a suspicion that the key is a virtual host with an illegal character in the name and an authconfig.

### Expected Behavior

should only happen when there is a change made.

**Comment by huzlak** [comment]
Related to https://github.com/solo-io/solo-projects/issues/4372

**Comment by sam-heilbron** [comment]
This bug has been fixed in the following versions of Gloo Edge Enterprise:
`1.14.0-beta3` (unreleased)
`1.13.4` (released)
`1.12.45` (released)
`1.11.51` (unreleased)

We tend to batch bug fixes in patch releases, so I would expect the 1.14 and 1.11 Enterprise versions to be released later this week. If that is not the case, or the fixes are needed sooner, please follow up here
