### ISSUE TITLE
knative install fails on enterprise version

### ISSUE THREAD

**Issue by marshall007** [solo-io/gloo#761]
Installing Knative components worked fine on the OSS version, but fails after I upgrade to the GlooE version of the CLI. I was unable to find any documentation indicating that installing Knative components is not currently supported by the enterprise version.

```
$ glooctl install knative --license-key <key>
this feature will be available soon

$ glooctl --version
glooctl enterprise edition version 0.13.17
```

**Comment by ilackarms** [comment]
hi @marshall007 sorry you ran into this missing feature. while we work to port the `glooctl install knative` command over to the Enterprise CLI, here's a workaround you can use in the meantime:

`glooctl install X` generates a kubernetes manifest and then uses `kubectl apply` on it. if you run with `--dry-run`, instead the manifest will be printed to stdout.

you may be able to simply run `glooctl install knative` with the oss, and then `glooctl install gateway` with the Enterprise to get Knative and Gloo Enterprise installed to your cluster. since the manifests use `kube apply` i believe this "might just work"

if it doesn't, what needs to be done is separate out the "knative components" from the OSS manifest (you can print the manifests with `glooctl install knative --dry-run`).

the components you need are:
- everything to install `knative-serving` itself (things that go in `knative-serving` namespace, plus their CRDs, cluster RBAC stuff, anything cluster-scoped)
- the `ingress` and `clusteringress-proxy` components of the gloo control plane.

if you install those parts on top of (or before) installing GlooEE, you should have both the enterprise Gloo Gateway as well as 

this is what the cli command will eventually automate, but it's not done yet. sorry for the inconvenience!

i think the first method (`glooctl-oss install knative` && `glooctl-ee install gateway`) should work!

**Comment by EItanya** [comment]
Consolidating CLI, no longer relevant
