### ISSUE TITLE
Gloo-EE Validating Webhook for Secrets Doesn't Work

### ISSUE THREAD

**Issue by Ido-Itz** [solo-io/gloo#8001]
### Gloo Edge Version

1.13.x (latest stable)

### Kubernetes Version

1.23.x

### Describe the bug

The Gloo-EE validating webhook is meant to be called during API "DELETE" operations on TLS secrets, and it should disallow the deletion in case there is an Upstream resource which references the secret.
However, as far as I could tell, the webhook isn't called when these secrets are deleted because the `rules` section on the `ValidatingWebhookConfiguration` resource doesn't include the correct GVK of the native Kubernetes secret resource.
Instead, it includes:
```yaml
- apiGroups:
  - gloo.solo.io
  apiVersions:
  - v1
  operations:
  - DELETE
  resources:
  - secrets
  scope: '*'
```
No CRD exists for a `gloo.solo.io/v1` `secret`, and the TLS Secrets are actually standard Kubernetes Secrets.

### Steps to reproduce the bug

1. Install Gloo-EE with the validating webhook enabled
2. Create an upstream with a reference to a TLS secret
3. Delete the secret
4. Secret is deleted

### Expected Behavior

When I delete the secret in the steps above, I should get an error from the API server telling me that the webhook doesn't allow it

**Comment by ashutosh887** [comment]
@Ido-Itz @SantoDE 
I would like to work on this... Please assign

**Comment by inFocus7** [comment]
## Release Information

### OSS
- [ ] v1.16.0-beta15
- [X] v1.15.11

### Enterprise
- [ ] v1.16.0-beta(2?)
- [ ] v1.15.(5?)

## Notes

Since we are now validating secret deletions, there is a possibility of slight performance hits in environments that constantly delete secrets. 

To avoid this, you can ignore secrets during validation, which would essentially act as it did before this change. There are two ways to do so:

### 1. Remove the `secret` rule from webhook config
Modify the `ValidatingWebhookConfiguration` resource (`gloo-gateway-validation-webhook-{namespace}`) and remove the `Secret` deletion rule.

### 2. Set the `skipDeleteValidationResources` through Helm
When upgrading/installing through Helm, set `gateway.validation.webhook.skipDeleteValidationResources={secrets}` to skip validating secret deletions.
