### ISSUE TITLE
Helm: Detect Poorly Formatted Templates

### ISSUE THREAD

**Issue by sam-heilbron** [solo-io/gloo#8268]
### Version

None

### Is your feature request related to a problem? Please describe.

Is is easy to unintentionally introduce whitespace in helm templates. This whitespace can range from being annoying (https://github.com/solo-io/gloo/pull/8265) to problematic (https://github.com/solo-io/gloo/issues/4645). We need to prevent these types of situations from entering the codebase in the first place, to avoid needing to fix them after the fact.

### Describe the solution you'd like

- [ ] Get https://github.com/solo-io/gloo/pull/8265 reviewed and merged
- [ ] Backport above changes to Gloo 1.13
- [ ] Identify a mechanism to validate templates via a test, which will fail when incorrect whitespace is introduced
- [ ] Introduce that mechanism in 1.15

### Describe alternatives you've considered

We have an existing test for trailing whitespace (https://github.com/solo-io/gloo/blob/main/install/test/helm_test.go#L6485) which we can use as a template and build out. There may also be better tools to solve this problem programatically.

**Comment by jackstine** [comment]
1. using `{{- ` and ` -}}`.
		1. There cannot be any instance of `{{` or `{{ ` or `}}` or ` }}` in our code.
2. Apparently `{{-` and `-}}` on the same line is very bad, because it will chomp the newlines on both sides of the equation. So something to prevent this.  There appears to be instances that this can be acceptable.
3. Have a program to verify that any next line is at most -2, 0, or +2 white spaces more than the previous line.
4. can use `helm lint` on the generated helm chart.  This can be added to our CI.
5. if we `make build-test-chart -B` then we can `helm template` to verify that the template gets generated successfully
	1. We can use `helm template` to identify white spacing issues, IE: `helm template`

**Comment by jackstine** [comment]
It seems that options (4) and (5) are already covered in our helm tests when we use the `BuildTestManifest()` to build out the yamls. Seems to output the same error in all three, something similar to the below.
```bash
error converting YAML to JSON: yaml: line 6: did not find expected key
```
