### ISSUE TITLE
Envoy Configuration showing Red in UI even though it says no issues with envoy

### ISSUE THREAD

**Issue by totallyGreg** [solo-io/gloo#8285]
### Gloo Edge Version

1.13.x

### Kubernetes Version

1.24.x

### Describe the bug

Customer reported this issue after updating to Gloo Edge 1.13.17

I have verified this in my own installation on GKE cluster

<img width="444" alt="image" src="https://github.com/solo-io/gloo/assets/283704/c41274c0-f530-46a8-8ca2-b23b796cf502">

There are no reported issues with the actual data plane configuration.  This appears to be a UI issue only.  

### Steps to reproduce the bug

Customer instance was an upgrade.  

I am seeing this same behavior in a glooctl upgrade of 1.13.12 I ran on April 13

### Expected Behavior

Customer would like to continue to use the admin view to accurately verify status of all the configurations.

**Comment by inFocus7** [comment]
Hey @totallyGreg! For clarification, when you saw the issue, was it a result from an upgrade? Or from a fresh installation of `1.13.12`?

**Comment by inFocus7** [comment]
Some EOD findings/updates:
- Manually reproduced this in multiple versions to see where the issue first began.
  - It was introduced in **EE `v1.13.0-beta9`**. 
  - The problem also exists starting in **EE `v1.12.35`**. So looks like something was backported.
- No UI changes have been made to the [specific component rendering this](https://github.com/solo-io/solo-projects/blob/4b206895655aaf02e7f783bc1569c1ae551f7a3d/projects/ui/src/Components/Features/GlooInstance/Admin/GlooInstanceAdminBoxSummary.tsx#L291-L319) in the last 2 years, so it's _maybe_ due to changes in the backend.
- There are instances where it's healthy/green for a few seconds then unhealthy with 0 proxies found. 
  - Weirdly enough, the amount of envoy proxies it "finds" is wrong where it states 10+, although there should only be 1: the `gloo-proxy`.
- Using React DevTools, I was able to see that the `glooInstance`'s `proxiesList` is empty which is why it's reporting `0`. **AND** when it "finds" the 10+ proxies and is "healthy", the `proxiesList` contains the exact same `gateway-proxy` repeated 10+ times, like so:
```json
# example of an object in the proxy list (which is getting repeated 10+ times, even though it should only be the 1 proxy.
{
  "replicas": 1,
  "availableReplicas": 1,
  "readyReplicas": 1,
  "wasmEnabled": false,
  "readConfigMulticlusterEnabled": false,
  "version": "1.14.3",
  "name": "gateway-proxy",
  "namespace": "gloo-system",
  "workloadControllerType": 1,
  "zonesList": [],
  "ingressEndpointsList": []
}
```

Still unsure about what code changes lead to this, but still decent findings.

Note: I reproduced it with `gloo-fed` disabled, since, after having it enabled + registering the cluster, no Gloo instances were found. I haven't worked with fed before, so I might've been missing something. This were my reproduction commands:
```
kind create cluster --image kindest/node:v1.24.0 && kubectl create ns gloo-system && helm install gloo glooe/gloo-ee --namespace gloo-system --set license_key=$GLOO_LICENSE_KEY --version 1.13.12 --set gloo.gatewayProxies.gatewayProxy.readConfig=true --set gloo.gatewayProxies.gatewayProxy.readConfigMulticluster=true --set gloo-fed.enabled=false
```
