### ISSUE TITLE
Adding the namespace field to the vault secret source. 

### ISSUE THREAD

**Issue by AkshayAdsul** [solo-io/gloo#8390]
### Version

None

### Is your feature request related to a problem? Please describe.

For Customer the Vault enterprise and Vault namespaces are security mandated to ensure isolation of credentials.
So they  can't  use the Vault Integration feature developed as part of https://github.com/solo-io/solo-projects/issues/4636 until support for Vault namespaces are added to Gloo edge. We will need to expose one more optional `namespace` field to vault secret source in settings.proto.

### Describe the solution you'd like

We would like the namespace option to be included below while specifying the vault details.
secretOptions:
    sources:
    - vault:
        accessToken: ********************************
        address: https://vault.***.com:8200
        aws:
          mountPath: xxx
          region: xxx
          vaultRole:xx
        caPath: xxx
        pathPrefix: xx
        rootKey: xxx
    - kubernetes: {}

### Additional Context

Original Github issue https://github.com/solo-io/solo-projects/issues/4636
Jacob/Sam/Manuel have been included in the email with customer which has further details.

**Comment by SantoDE** [comment]
This is a bit controversial to https://github.com/solo-io/solo-projects/issues/5007. We need to see what we can do with both of that issues together.

**Comment by sam-heilbron** [comment]
A great find from @jbohanon : 

https://github.com/hashicorp/vault/blob/main/api/client.go#L592-L655 The vault namespace property can be configured programmatically via the `VAULT_NAMESPACE` env variable. If you configure this on the Gloo pod, the namespace functionality should be functional.

If this works, we can expose this in our API on the Settings object, like the other Vault configuration.

**Comment by sam-heilbron** [comment]
Assigning to @AkshayAdsul @pseudonator to test these findings out and report back. When you have details, can you follow up on this issue, tag me in Slack, an re-assign me?

**Comment by sam-heilbron** [comment]
Internal links:
- [Reproduction findings](https://docs.google.com/document/d/1M8ZFPfkMbfKjwc-_7DWy0LQUvVjw-iMpGxV4CqRh2Lk/edit)
- [Slack conversation](https://solo-io-corp.slack.com/archives/C041655PEFR/p1689953663958429)

**Comment by sam-heilbron** [comment]
There seem to be 2 pieces of work at play here
1. Requirement of aws env variables. We currently error if they are not provided.
2. The initial list of secret/dev/metadata/gloo/gloo.solo.io/v1/Secret/ contained no values, and as a result we panic

(1)
I agree, if there are environments where this isn't required and instead inferred, we should mirror that in Edge. We can confirm this with product, but perhaps we just log a warning instead that the variables aren't provided

(2)
failed warming up endpoints - consider adjusting endpointsWarmingTimeout is intentional, but we also provide an endpointsWarmingTimeout in the Settings resource to help with slow starts. If there is just latency in accessing those secrets, I would increase that value. If they will never be accessed, then it seems like the config for the secret store is not configured properly. In the Vault app can you see the secrets at that path? Does this just occur when "multiple secret sources" is configured or also when using hte old API? In gloo, based on the configuration, we look at a specific vault path (secret/dev/metadata/gloo/gloo.solo.io/v1/Secret/ for the secrets)

**Comment by AkshayAdsul** [comment]
I will open a new RFE, that calls out supporting IAM roles in AWS auth for vault.
As mentioned above the vault namespace property can be configured programmatically via the VAULT_NAMESPACE env variable.
