### ISSUE TITLE
9-gateway-proxy-configmap changes should restart proxies

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#8392]
### Version

1.13

### Is your feature request related to a problem? Please describe.

Currently proxy configmap changes dont cause a rollout of the proxies. Customer would like any change to the configmap to restart the proxies automatically.

### Describe the solution you'd like

https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

### Describe alternatives you've considered

manual rollout

**Comment by SantoDE** [comment]
Probably more important to rollout after helm changes, rather then direct file edits.

**Comment by davidjumani** [comment]
Fixed in OSS [v1.13.28](https://github.com/solo-io/gloo/releases/tag/v1.13.28), [v1.14.22](https://github.com/solo-io/gloo/releases/tag/v1.14.22), [v1.15.9](https://github.com/solo-io/gloo/releases/tag/v1.15.9) && [v1.16.0-beta14](https://github.com/solo-io/gloo/releases/tag/v1.16.0-beta14)
Fixed in Enterprise [v1.13.27](https://github.com/solo-io/solo-projects/releases/tag/v1.13.27), [v1.14.11](https://github.com/solo-io/solo-projects/releases/tag/v1.14.11), [v1.15.5](https://github.com/solo-io/solo-projects/releases/tag/v1.15.5) and v1.16.0-beta2 when released
