### ISSUE TITLE
Ability to change UIDs for static and dynamic dashboards so they do not conflict across multiple Gloo environments

### ISSUE THREAD

**Issue by edubonifs** [solo-io/gloo#9022]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.15.x

### Is your feature request related to a problem? Please describe.

One of our customers is asking to provide them the ability to provide unique UIDs for the static dashboards and dynamic dashboards, so they do not conflict across multiple Gloo environments

Ideally it is a helm override, for instance dashboard prefix (for instance: dev). The dashboard prefix is then used as prefix to static and dynamic dashboards.

**Comment by kcbabo** [comment]
Related: https://github.com/solo-io/gloo/issues/6536

**Comment by kcbabo** [comment]
#9016 and #9022 need to be tackled together to solve the overall problem.

**Comment by davidjumani** [comment]
Have discussed with @edubonifs and decided that the prefix will apply to the title of the dashboard as well

**Comment by davidjumani** [comment]
Discussing with @edubonifs and decided that any existing dashboards without the prefix or with a different prefix will need to be manually removed as doing so automatically can cause issues. Eg: If an environment with the `dev-` prefix has now been modified to `stage-` and a new environment has been added with the `dev-` prefix, there is a possibility that the dashboards created by the latter environment will be deleted due to the change in the prefix of former environment.

**Comment by davidjumani** [comment]
Additional docs PR https://github.com/solo-io/gloo/pull/9074

**Comment by davidjumani** [comment]
This will be in v1.17.0-beta1, v1.16.1 and v1.15.12 when released
