### ISSUE TITLE
Improve docs on preferred ways to route to K8S Services and Pods

### ISSUE THREAD

**Issue by DuncanDoyle** [solo-io/gloo#9164]
### Version

main (1.16.x beta)

### Describe the requested changes

Routing from Gloo Edge directly to K8S Services (i.e. not using Upstreams) can have a negative impact on performance:

- First, routing is done to the K8S Service and not the Pods directly, and hence load-balancing is not done in Envoy but in kube-proxy.
- Second, on clusters with a large number of services, having the option to route to K8S Services can introduce unnecessary overhead: https://github.com/solo-io/gloo/issues/1466

In our documentation, we don't mention that routing to K8S Services directly is not recommended: https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/kubernetes_services/

We should add this information to our docs and advise users to use Upstreams instead of using K8S Services as destination types.

### Link to any relevant existing docs

1. https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/kubernetes_services/

### Browser Information

n.a

### Additional Context

n.a

# Related Issues:

This improvement was suggested in: https://github.com/solo-io/solo-projects/issues/5343 , in particular in [this comment](https://github.com/solo-io/solo-projects/issues/5343#issuecomment-1815010194).

Additional information in [this Slack thread](https://solo-io-corp.slack.com/archives/C04A26WSZ43/p1700158820360819?thread_ts=1699993565.562579&cid=C04A26WSZ43).

**Comment by Nadine2016** [comment]
https://github.com/solo-io/gloo/pull/9194

**Comment by sam-heilbron** [comment]
## Option A: Routing to the Kubernetes Service directly
This works by routing traffic from the client, through the gateway-proxy, directly to the Kubernetes Service. As @DuncanDoyle points out, this means that we are relying on the kube-proxy as opposed to our gateway-proxy for upstream load balancing.

This option is configured via the API:
```
routes:
- matchers:
   - prefix: /petstore
  routeAction:
    single:
      kube:
        ref:
          name: petstore
          namespace: default
        port: 8080
```

The ControlPlane relies on a Gloo primitive, the Upstream CR, to define upstream workloads. This is meant as a generic API to apply to upstream workloads as this may be a kubernetes service, or any other type of destination. Because of this API, we have logic to validate that [upstream destinations are in fact valid](https://github.com/solo-io/gloo/blob/main/projects/gloo/pkg/translator/route_config.go#L846). This works by performing the following steps:
1. Convert a "destination" into the Upstream reference (name/namespace)
2. Inspect the API Snapshot (the full set of resources that Gloo is aware of) to see if that Upstream ref exists
3. Error if not

As a result, to allow for routing to a Kubernetes Service directly, Gloo must create an Upstream CR to represent the config (and therefore it is in the API Snapshot, and the above linked code does not return an error).
In order to generate the Upstream, Gloo must:
1. Poll the list of Kubernetes Services (https://github.com/solo-io/gloo/blob/main/projects/gloo/pkg/upstreams/hybrid_client.go#L50)
2. Update the internal memory to store those Upstream representations

_This action has been proven to be more resource exhaustive_


## Option B: Routing to the Kubernetes Service via the Standard Upstream API
Instead of routing to a Kubernetes Service, you can route to the endpoints that a Kubernetes Service represents.

This is done via the Upstream API: https://github.com/solo-io/gloo/blob/ce7474cb3c364239c00f09f203980143a706e8b8/projects/gloo/api/v1/options/kubernetes/kubernetes.proto#L18

The ControlPlane will then execute an EDS loop (https://github.com/solo-io/gloo/blob/main/projects/gloo/pkg/plugins/kubernetes/eds.go#L88) in which the Upstreams are processed, and the ControlPlane continually resolves the available pods/endpoints to pass along to the gateway-proxy.

**Comment by Nadine2016** [comment]
https://github.com/solo-io/gloo/pull/9196

**Comment by Nadine2016** [comment]
this is in prod https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/kubernetes_services/ closing
