### ISSUE TITLE
enable k8s gateway extensions to force resync xds

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#9330]
### Gloo Edge Product

Open Source

### Gloo Edge Version

v1.17.0-beta17

### Is your feature request related to a problem? Please describe.

To support extensions like Portal which initialize their own watches on CRDs the xds snapshot does not contain, extensions need to be able to 'kick' XDS translation, e.g. indicate to the gateway controller to re-reconcile gateways so a specific plugin can re-run its logic in step with XDS (i.e. a new APIProduct added, we will need to update the transformation filters we apply to routes)

**Comment by inFocus7** [comment]
accidentally got closed with the oss' merger, although still has work in-review in EE

**Comment by inFocus7** [comment]
While the PR is merging, one thing I noticed was that when deleting a generated **PortalConfig**, it _does not_ automatically get regenerated. At least not until a Gloo resource or something else that kicks of xds/translation occurs.

We _could_ create another watch + reconciler for it, similar to the ones created in the enterprise PR. I tried it locally and can verify it works when manually tested. The issue is that the **PortalConfig** is an outputted resource, so not sure if we really need to watch it, or of it's overkill to do so. 

---

@jmhbh and I will ask Scott for opinions on Monday.
