### ISSUE TITLE
enable traffic shadowing

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#934]
the feature already exists in envoy, just needs to be exposed in our api via a simple plugin

**Comment by mitchdraft** [comment]
planned api:
```proto
// Specifies traffic shadowing configuration for the associated route.
// See here for additional information on Envoy's shadowing capabilities: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route.proto#envoy-api-msg-route-routeaction-requestmirrorpolicy
message RouteShadow {
    // The upstream to which the shadowed traffic should be sent.
    core.solo.io.ResourceRef upstream_ref = 1;

    // the percent (represented as an integer between 0 and 100) of traffic that should be shadowed
    uint32 percent = 2;
}
```
will use `translator.UpstreamToClusterName(upstream.Metadata.Ref())` to get the cluster from the upstream

shadowing seems only to be a property of the route (in envoy) (rather than the listener) so I will just implement shadowing as a route plugin

We could do something with groups of routes, for example, all routes that go to upstreamX should also be shadowed to upstreamY - but maybe we leave that for V2?

does that seem reasonable to you @ilackarms ?

**Comment by ilackarms** [comment]
yeah i think this is a great starting place. route is good enough for now (though could be interesting to consider something clever on the upstream or vhost level at some point)
