### ISSUE TITLE
unclear behavior  with  prefixRewrite

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#992]
When people want to strip a prefix from a  route it is  unclear how to set `prefixRewrite` option

is it `prefixRewrite: ""` (no space) or `prefixRewrite: "  "` (with space) or `prefixRewrite: "/"`?

need to  at least clarify in doc, and ideally update code behavior so empty string implies strip prefix, i.e. more intuitive than a space to indicate strip prefix.

**Comment by leosunmo** [comment]
Not that familiar with the Envoy code, but https://github.com/cmluciano/envoy/blob/f01d41766bd664ac5e9e7b62661df3e8db653530/source/common/router/config_impl.h#L392 looks like it just ignores it if it's empty?

Adding a Gloo function that translates `""` to `" "` probably wouldn't hurt since it's not overwriting any functionality in Envoy, just a bit of extra user-friendliness.

`"/"` on the other hand means something completely different.

To start with just updating the docs _with an example_ and change the wording to be very clear about `""` being a no-op and `" "` actually removing the prefix.

**Comment by scranton** [comment]
and prefixRewrite: " " (space) replaces the prefix with an actual space in the HTTP :path header which confuses things like Knative activator.

**Comment by leosunmo** [comment]
Yeah I forgot to mention it literally puts a space in there! :P

The space doesn't matter for my purpose (yet...) but getting rid of the double prefix rewrite would be excellent!

**Comment by ilackarms** [comment]
opened an issue which tracks the relevant piece of code: #1373

**Comment by scranton** [comment]
bump this issue as its still confusing for users

**Comment by eshepelyuk** [comment]
I would introduce special new option for this case. e.g. `--strip-prefix`
For instance Kong has this option in their config.

**Comment by rickducott** [comment]
https://github.com/solo-io/gloo/issues/1373
